### ISSUE TITLE
Support for 14.04

### ISSUE THREAD

**Issue by zayim** [arachnys/cabot#122]
Currently, latest LTS of Ubuntu supported by cabot is 12.04, trying to install on 14.04 I get an error, not all dependencies are available. We can change install_dependencies.sh script, but it would be nice if 14.04. is supported without having to change source.

**Comment by JulienChampseix** [comment]
@dbuxton is it planned to merge the fix from @packetcollision to the master branch ? for support 12.04/14.04

**Comment by JulienChampseix** [comment]
For 14.04, i got this error running fab deploy -H ubuntu@localhost

[ubuntu@localhost] out: Successfully installed Django Markdown South django-compressor django-filter django-polymorphic djangorestframework gevent psycogreen pytz cabot greenlet
[ubuntu@localhost] out: Cleaning up...
[ubuntu@localhost] out:

[ubuntu@localhost] sudo: foreman run python manage.py syncdb -e conf/production.env
[ubuntu@localhost] out: /usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find foreman (>= 0) amongst [actionmailer-4.2.0, actionpack-4.2.0, actionview-4.2.0, activejob-4.2.0, activemodel-4.2.0, activerecord-4.2.0, activesupport-4.2.0, arel-6.0.0, builder-3.2.2, bundler-1.8.2, bundler-unload-1.0.2, erubis-2.7.0, executable-hooks-1.3.2, gem-wrappers-1.2.7, globalid-0.3.3, hike-1.2.3, i18n-0.7.0, loofah-2.0.1, mail-2.6.3, mime-types-2.4.3, mini_portile-0.6.2, minitest-5.4.3, multi_json-1.10.1, nokogiri-1.6.6.2, power_assert-0.2.2, rack-1.6.0, rack-test-0.6.3, rails-4.2.0, rails-deprecated_sanitizer-1.0.3, rails-dom-testing-1.0.5, rails-html-sanitizer-1.0.1, railties-4.2.0, rubygems-bundler-1.4.4, rvm-1.11.3.9, sprockets-2.12.3, sprockets-rails-2.2.4, test-unit-3.0.8, thor-0.19.1, thread_safe-0.3.4, tilt-1.4.1, tzinfo-1.2.2] (Gem::LoadError)
[ubuntu@localhost] out: 	from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
[ubuntu@localhost] out: 	from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
[ubuntu@localhost] out: 	from /usr/local/bin/foreman:22:in `<main>'
[ubuntu@localhost] out:


Fatal error: sudo() received nonzero return code 1 while executing!

Requested: foreman run python manage.py syncdb -e conf/production.env
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "cd /home/ubuntu/2015-02-19-ef09cb4 && source /home/ubuntu/venv/bin/activate && foreman run python manage.py syncdb -e conf/production.env"

Aborting.
Disconnecting from localhost... done.
sudo() received nonzero return code 1 while executing!

Requested: foreman run python manage.py syncdb -e conf/production.env
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "cd /home/ubuntu/2015-02-19-ef09cb4 && source /home/ubuntu/venv/bin/activate && foreman run python manage.py syncdb -e conf/production.env"

Any idea ?

**Comment by dbuxton** [comment]
Seems foreman is not installed. Did you run fab provision? (Caution because
that will create a new user and lock you out of root)

**Comment by JulienChampseix** [comment]
@dbuxton you was right! 2 gems lib was missed which was fixed by running 'gem install foreman' but new error looks appear : 

[ubuntu@localhost] run: ln -sfn /home/ubuntu/2015-02-19-ef09cb4 /home/ubuntu/cabot
[ubuntu@localhost] sudo: foreman export upstart /etc/init -f /home/ubuntu/cabot/Procfile -e /home/ubuntu/cabot/conf/production.env -u ubuntu -a cabot -t /home/ubuntu/cabot/upstart
[ubuntu@localhost] out: [foreman export] writing: cabot.conf
[ubuntu@localhost] out: [foreman export] writing: cabot-web.conf
[ubuntu@localhost] out: [foreman export] writing: cabot-web-1.conf
[ubuntu@localhost] out: [foreman export] writing: cabot-celery.conf
[ubuntu@localhost] out: [foreman export] writing: cabot-celery-1.conf
[ubuntu@localhost] out:

[ubuntu@localhost] sudo: restart cabot
[ubuntu@localhost] out: restart: Unknown instance:
[ubuntu@localhost] out:


Warning: sudo() received nonzero return code 1 while executing 'restart cabot'!

[ubuntu@localhost] sudo: start cabot
[ubuntu@localhost] out: cabot start/running
[ubuntu@localhost] out:

Done!

Done.
Disconnecting from localhost... done.


Is it a normal one ?

**Comment by dbuxton** [comment]
Hmm I'm not sure about this. Maybe upstart not there?

**Comment by JulienChampseix** [comment]
@dbuxton cabot is reachable, looks working. Any idea how to use add influxdb check ? @bonniejools was working on this plugins i think

**Comment by dbuxton** [comment]
Check plugins are not there yet

**Comment by JulienChampseix** [comment]
ah ok i thouhgt, do you know if there is a devel branch containing first version of plugins ? or know when a first version will be released ?

**Comment by JulienChampseix** [comment]
Into log i got this :

pkg_resources.DistributionNotFound: pytz>dev
Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/celery", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pytz>dev

**Comment by packetcollision** [comment]
Can you tell me a bit more about your 14.04 installation? I tested it on 64-bit Amazon and Vagrant, but maybe there are issues with another provider.

The steps should be exactly the same as described in the 12.04 installation guide.

**Comment by bonniejools** [comment]
@JulienChampseix check plugins are being developed in #187 so you can follow/comment on the development there. It is still rather primitive at the moment and the plugin architecture hasn't been fully defined yet.

@packetcollision It looks like the differences between 12.04 and 14.04 are just package naming conventions so it should work absolutely fine once deployed. I'll test a vps deploy and get vagrant going but otherwise I see no reason not to merge.

**Comment by packetcollision** [comment]
@bonniejools Exactly, 14.04 support just means changing a few package names and adding the ability to select the Vagrant box. I've been running Cabot deployed from this branch in production for a month at least.

**Comment by JulienChampseix** [comment]
Can you re-open it ?

Still having issue from the log for support Ubuntu 14.04 (from fresh install) :
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
Linux 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
Install done on physical ( PowerEdge M600 ) 

History of the install:
echo "deb http://deb.theforeman.org/ trusty 1.5" > /etc/apt/sources.list.d/foreman.list
echo "deb http://deb.theforeman.org/ plugins 1.5" >> /etc/apt/sources.list.d/foreman.list
apt-get update && apt-get install foreman-installer
git clone -b ubuntu1404 https://github.com/packetcollision/cabot.git
cd cabot
cp conf/production.env.example conf/production.env
fab provision -H root@localhost
fab deploy -H ubuntu@localhost

Following that i got this error (but cabot was running):


Into /var/log/cabot/celery-1.log:
Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/celery", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pytz>dev

When i try to force a run over :
http://10.10.17.6/check/run/1/

I got this error:
 Unhandled error. Please look at logs.

**Comment by packetcollision** [comment]
I'll do a manual install of Ubuntu 14.04 and doc any errors I have, probably in the next day or so. It's certainly possible that some required packages come pre-installed on Vagrant/EC2 that we need to explicitly install for bare-metal.

**Comment by packetcollision** [comment]
@JulienChampseix

**Comment by packetcollision** [comment]
@JulienChampseix try activating the cabot venv (`source /home/ubuntu/venv/bin/activate`) and running `pip install --upgrade Distribute` (you might need to run `chown -R ubuntu /home/ubuntu/venv`) first. Let me know if that works, and I'll see about getting the fix into the source. 

I'm still not sure why it work on my vagrant and my EC2 setups but not on a standard ubuntu-server install. It may actually be a red herring: the issue might be installing to localhost. I'll test more tomorrow.

**Comment by JulienChampseix** [comment]
Thks for your feedback

I'll try tomorrow to upgrade Distribute

Have you do more test based on localhost ?

**Comment by JulienChampseix** [comment]
@packetcollision @dbuxton 
I ran :
pip install --upgrade Distribute
Collecting Distribute
  Downloading distribute-0.7.3.zip (145kB)
    100% |################################| 147kB 1.4MB/s
Collecting setuptools>=0.7 from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-12.3-py2.py3-none-any.whl#md5=31f51a38497a70efadf5ce8d4c2211ab (from Distribute)
  Downloading setuptools-12.3-py2.py3-none-any.whl (501kB)
    100% |################################| 503kB 721kB/s
Installing collected packages: setuptools, Distribute
  Found existing installation: setuptools 3.3
    Uninstalling setuptools-3.3:
      Successfully uninstalled setuptools-3.3

  Running setup.py install for Distribute
Successfully installed Distribute-0.7.3 setuptools-12.3

Same error :

==> /var/log/cabot/web-1.log <==
2015-02-27 14:09:42 [3597] [INFO] Starting gunicorn 18.0
2015-02-27 14:09:42 [3597] [INFO] Listening at: http://127.0.0.1:5000 (3597)
2015-02-27 14:09:42 [3597] [INFO] Using worker: sync
2015-02-27 14:09:42 [3619] [INFO] Booting worker with pid: 3619
2015-02-27 14:09:42 [3629] [INFO] Booting worker with pid: 3629
2015-02-27 14:09:42 [3667] [INFO] Booting worker with pid: 3667

==> /var/log/cabot/celery-1.log <==
Traceback (most recent call last):
  File "/home/ubuntu/venv/bin/celery", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntu/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pytz>dev

**Comment by JulienChampseix** [comment]
@packetcollision  @dbuxton Can we re-open it ?

**Comment by dbuxton** [comment]
@packetcollision did your investigations get anywhere?

**Comment by JulienChampseix** [comment]
@packetcollision have you did more test ?

**Comment by packetcollision** [comment]
It seems to be a 14.04-wide issue, although my already set up systems are fine. I started a new job a few weeks ago and I haven't had time to do anything related to Cabot since then, but I'll keep working on this when I can find the time.

**Comment by markdanko** [comment]
I have also run into this issue.  Is there a work around for this?

**Comment by grzegorz-dubicki** [comment]
+1

I am seeing the same messages as https://github.com/arachnys/cabot/issues/122#issuecomment-75213610 EXCEPT my force check over DOESN'T results in an error - the HTTP check seems to be working.

**Comment by vood** [comment]
Just wanted to post here my workaround. It turned out that ~/venv had permission issues on ubuntu 14.04. I did the following ```sudo chown ubuntu /home/ubuntu/venv -R``` and then ```pip install celery --upgrade```. It resolved the issue.

**Comment by nickmileiq** [comment]
Thank you @vood! That workaround worked for me.

**Comment by vood** [comment]
@nickmileiq glad it helped.

**Comment by mattvonrocketstein** [comment]
I'll throw this out there as an argument for better out-of-box support for ubuntu 14.04: I'm interested in cohosting cabot / graphite on the same server and I bet a lot of people who are just experimenting or only building smallish metrics/monitoring solutions are the same.  Ubuntu 14.04 is much easier to build graphite on, so it would be nice if cabot "just worked" there too.  Graphite is the more complicated app, so changing cabot to support 12.04 and 14.04 is the easier path.  (See for example [this](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-graphite-on-an-ubuntu-14-04-server) tutorial on the graphite installation.. for 12.04 the situation is worse)

**Comment by pabl0rg** [comment]
@mattvonrocketstein i guess you could use docker.  Cabot is pretty cool, but connecting cabot + graphite + whisper is so much more complicated than using influxdb + chronograf + capacitor

```
curl -sL https://repos.influxdata.com/influxdb.key | apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | tee -a /etc/apt/sources.list

apt-get update
apt-get install influxdb telegraf chronograf kapacitor
```

**Comment by gdm85** [comment]
I think also 16.04 LTS should be supported, eventually (there is no issue for that)..

**Comment by JeanFred** [comment]
I have successfully deployed Cabot (latest master) on Ubuntu Trusty 14.04. I did not use the Fab script but an Ansible role (I’ll see if I can share it somewhere). Barring some issues with the Django upgrade (since fixed), it worked fairly out of the box. I’m this tempted to close this?

**Comment by pabl0rg** [comment]
Switching to ansible would be huge.  Can you please post to this issue when/where you do it?

**Comment by JeanFred** [comment]
@pabl0rg It’s here : https://github.com/cabotapp/ansible-cabot Note that since we have moved to pip packages, it’s much much easier to install Cabot, and the role does not do that much :)

**Comment by JeanFred** [comment]
@gdm85 At Arachnys we are now running Cabot on Ubuntu Xenial, and it’s working great :)
