### ISSUE TITLE
Cabot stops checks from running after Ubuntu reboot

### ISSUE THREAD

**Issue by go-online** [arachnys/cabot#134]
Just installed Cabot for the 10th time... Great app.

After provisioning and deploying successful - everything is great. I create some graphite checks and the automatically running as expected according to my frequency preferences.

BUT:
If we'll look into the hosted VM (I'm using putty), Ubuntu tells me between the lines:

> restart required

(It's just a recomendation, I can keep doing stuff with the command line, but I'm like these guys who does what the machine tells him to do..:)

So I'm doing "sudo reboot", and in a few minutes the VM is up and running again, but it seems that checks are no longer running. They just stuck on the last check (timestamp can be found under "Time complete" column in the check's page).

If you'll try to run the check manually ("refresh" button, top-right) the browser goes to a page with message: **"Unhandled error. Please look at logs."**

(At this point I'm also getting an email with subject "**[Django] ERROR (EXTERNAL IP): Internal Server Error: /check/run/1/**" - and a nice log inside it).

So I went to see the logs (BTW - which logs?).

$ tail /var/log/cabot/celery-1.log :

> [2014-10-15 08:56:46,902: ERROR/Beat] beat: Connection error: invalid password. Trying again in 32.0 seconds...
> [2014-10-15 08:57:18,653: ERROR/MainProcess] consumer: Cannot connect to redis://@localhost:6379/1: invalid password.
> Trying again in 32.00 seconds...
> 
> [2014-10-15 08:57:19,029: ERROR/Beat] beat: Connection error: invalid password. Trying again in 32.0 seconds...
> [2014-10-15 08:57:50,781: ERROR/MainProcess] consumer: Cannot connect to redis://@localhost:6379/1: invalid password.
> Trying again in 32.00 seconds...
> 
> [2014-10-15 08:57:51,157: ERROR/Beat] beat: Connection error: invalid password. Trying again in 32.0 seconds...

$ tail /var/log/cabot/web-1.log

>   self.send_packed_command(self.pack_command(*args))
>   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/redis/connection.py", line 311, in send_packed_command
>     self.connect()
>   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/redis/connection.py", line 257, in connect
>     self.on_connect()
>   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/redis/connection.py", line 287, in on_connect
>     if nativestr(self.read_response()) != 'OK':
>   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/redis/connection.py", line 339, in read_response
>     raise response
> ResponseError: invalid password

It seems that cabot _is_ trying to run checks every 2 minutes (as I asked), but it encounters "invalid password"...?

"sudo service cabot restart" won't help, **So YOUR help is much appreciated!**

Thanks

**Comment by grzegorz-dubicki** [comment]
I'd like to add to what @go-online wrote above: Cabot's redis default password actually is "yourredispassword". So it's not a placeholder to replace with an actual value but IT IS the actual value. :)
