### ISSUE TITLE
Instances vs. Services

### ISSUE THREAD

**Issue by Duologic** [arachnys/cabot#137]
What is the idea behind Instances and Services? It seems I can't find any explanation in the docs/code.

Through trial and error I've found the following:
- Services have Alerts
- Instances don't have Alerts
- Instances can have ICMP
- Services can have ICMP **but** with a workaround (Edit the Service and add them there)
- ICMP does not work without an Instance
- ICMP does not alert without a Service (and you will want to get an alert!)
- Instances and Services can have relations, this is only interesting for semantic reasons

Except for making ICMP work, there is only the semantic advantage.
It all seems a bit too complicated to me, but maybe someone can enlighten me here?

**Comment by grzegorz-dubicki** [comment]
You can try to read the docs I have added with my PR some time ago: http://cabotapp.com/use/instances.html

And if they are not clear please try to improve them and create a new PR (that page is in this repo, in gh-pages branch).

**Comment by xinity** [comment]
Been working on alerting for instances (failing as today implementing it) instances are related to servers /vm/container... As services are related to i.e apache cluster, mysql, Web apps..... If some would help adding alerts to instances that would be awesome

**Comment by josegonzalez** [comment]
Seems like this can be closed, as instances are documented?
