### ISSUE TITLE
Check succeeds even if there is no data

### ISSUE THREAD

**Issue by Gromph** [arachnys/cabot#140]
I'm using diamond to send system metrics to graphite, I wanted to see what would happen if diamond stopped reporting. I expected the checks to start failing, but they don't. 

Metric:
servers.www01.diskspace.root.gigabyte_percentfree

Check Type: Less than
Value: 50
Frequency: 1

Raw Data examples where the check passes:
[{"target": "servers.www01.diskspace.root.gigabyte_percentfree", "datapoints": [[43.11, 1415120880], [43.11, 1415120940], [43.11, 1415121000], [null, 1415121060], [null, 1415121120], [null, 1415121180], [null, 1415121240], [null, 1415121300], [null, 1415121360], [null, 1415121420]]}]

[{"target": "servers.www01.diskspace.root.gigabyte_percentfree", "datapoints": [[null, 1415121120], [null, 1415121180], [null, 1415121240], [null, 1415121300], [null, 1415121360], [null, 1415121420], [null, 1415121480], [null, 1415121540], [null, 1415121600], [null, 1415121660]]}]

**Comment by hummal** [comment]
@dbuxton having the same problem. After 4 years PR ready? :)
