### ISSUE TITLE
Jenkins check failing

### ISSUE THREAD

**Issue by romankor** [arachnys/cabot#143]
I have a problem configuring a simple jenkins check:

![image](https://cloud.githubusercontent.com/assets/2689706/4918408/fb0ce8ba-64f0-11e4-95d7-ee7ea398c433.png)

That is what I see in the check , i tried to see whether there is more info on the exception in the cabot logs , but didnt find anything there.

Thanks

**Comment by AvihayTsayeg** [comment]
I meet the same issue.

**Comment by doboy** [comment]
+1

**Comment by frankh** [comment]
It's hard to tell what the issue is without more information

My gut says probably either bad auth credentials, or pointing to e.g. http://jenkins... instead of https:

**Comment by thomasleveil** [comment]
I hit the same bug with 0.11.8, is there anything that can be set in the conf to make the full backtrace appear in the log?

**Comment by JeanFred** [comment]
A typical instance « No attribute __get_item__»  is when there is no build yet for a job. Could that be it ?

**Comment by thomasleveil** [comment]
yep, that was it. It had created a new job just for the purpose of validating the migration to 0.11.8. That's a bit confusing, could that case be detected and a nice message displayed?

**Comment by JeanFred** [comment]
@thomasleveil Just opened #567 for this :)

**Comment by JeanFred** [comment]
Closing this as resolved then :)
