### ISSUE TITLE
Alerts on no recent data in graphite

### ISSUE THREAD

**Issue by 0rc** [arachnys/cabot#175]
Are there any plans to implement alerting on no recent data coming to graphite?
For example if we don't have any new data for some metric for last N minutes we might assume something goes wrong and alert on this
I would imagine this as an additional parameter of each graphite check
Or may be I missed something and this is already in place?

**Comment by bonniejools** [comment]
[There is documentation here](http://cabotapp.com/use/graphite-checks.html).

Essentially, you can set 'Expected number of hosts' option to the number of hosts that you expect to be supplying data for a particular metric to Graphite. If the real number falls below this threshold, the test will fail.

**Comment by 0rc** [comment]
Actually it's not the same
For example, if I have N machine cluster and M minimum copies of some applications expected to be running at any given time, N > M
All N machines are reporting some metric to graphite, 1 in that metric indicates that given host is running 1 copy of given app and 0 is indicating that it is not running any copies of given app
If I set "expected number of hosts" to either N or M it doesn't works properly for my use case
So it would be great to have possibility to set something like "expected number of values that are satisfying given condition" instead of or in addition to "expected number of hosts"

**Comment by 0rc** [comment]
@dbuxton can you please reopen the issue

**Comment by dbuxton** [comment]
I see what you mean, it's quite complicated isn't it not so much from a check point of view but from a UX point of view - `expected_num_hosts` is pretty opaque. I think this is easy enough to implement technically but documentation should also be very clear.

**Comment by 0rc** [comment]
ok so if there is no such functionality currently I am willing to start work on implementing this
will appreciate any help with documentation and/or code

**Comment by dbuxton** [comment]
It should be easy enough, you will have to look at the `GraphiteCheck` to see how it is currently implemented...

**Comment by 0rc** [comment]
Created pull request

**Comment by 0rc** [comment]
any response please?

**Comment by dbuxton** [comment]
Sorry missed this. Will have a look in next few days.

**Comment by 0rc** [comment]
thanks

**Comment by 0rc** [comment]
closed
