### ISSUE TITLE
cabot.settings

### ISSUE THREAD

**Issue by octavianlaies** [arachnys/cabot#176]
Hello,

I'm working on setting up a production cabot server however I have an issue with getting it to run.
I use the latest version of cabot and the versions of the dependencies in setup.py and I'm trying to run it with uwsgi.

The server starts but I get an error:
Site matching query does not exist.

I read up on that and I would expect that to be defined in cabot.settings because that is specified in the environment for DJANGO_SETTINGS_MODULE however I can't find an example of this file anywhere. Is this how it's supposed to work?

I apologize, I'm not a python developer.

Thank you

**Comment by octavianlaies** [comment]
Also, assuming I do have the file, what is the best way to make that visible to Django?

**Comment by dbuxton** [comment]
Best to try with the quickstart guide http://cabotapp.com/qs/quickstart.html - this is a general django configuration issue and not to do with Cabot in particular
