### ISSUE TITLE
Service passing even though check fails

### ISSUE THREAD

**Issue by octavianlaies** [arachnys/cabot#178]
Hello,

I configured a service and added a check to it. My check shows up as critical however the status in the service list says Overall:passing.
What am I missing?

Thank you

**Comment by dbuxton** [comment]
I suspect that this is also a consequence of #177 - do you have any errors in your logs that indicate that there is an error updating the service?

**Comment by octavianlaies** [comment]
It was a consequence of 177. Thanks.
