### ISSUE TITLE
UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!

### ISSUE THREAD

**Issue by octavianlaies** [arachnys/cabot#179]
Hi, 

This is probably a python noob question again but I get this warning:
UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
I read the Django documentation on how to disable this so I have to set DEBUG="False" however I double checked and I use 'export DEBUG="False";' in the Upstart config which I would expect would also take Django out of debug. Is that not the case?

**Comment by dbuxton** [comment]
In Python `"False`" is truthy (it's a non-empty string). `DEBUG=False` in `settings.py` should work.

Just leave the DEBUG line out of your upstart config altogether (or put `DEBUG=`) and don't mess around with the `settings.py` value. That should work
