### ISSUE TITLE
Layout Issue - Header is Hidden

### ISSUE THREAD

**Issue by octavianlaies** [arachnys/cabot#180]
I've got an issue with the page layout:
In Safari 8.0.3, I navigate to Services for example, I get the list of services, however if I scroll up I can see a header with "Services" and an add button to the right side. I cannot get it to show completely however, I "rubber bands" back up below the top bar.
In Chrome 40.0.2214.111 and Firefox 35.0.1 the content doesn't scroll so that section isn't displayed at all. The section is the dom though but it's covered by the bar.
I'm using OS X Yosemite.

**Comment by dbuxton** [comment]
I can't replicate this, sorry. Maybe there's some issue with the build process on your instance and the less file (`static/arachnys/css/base.less`) isn't getting compiled by django-compressor?

**Comment by octavianlaies** [comment]
I checked and the file is in the static folder where the files get compressed.
The rest of the layout is fine, it's just this small issue that is happening.
