### ISSUE TITLE
Migration 10 is failing on new install

### ISSUE THREAD

**Issue by candland** [arachnys/cabot#188]
[cabot] sudo: foreman run python manage.py migrate cabotapp --noinput -e conf/production.env
[cabot] out: Running migrations for cabotapp:
[cabot] out:  - Migrating forwards to 0011_plugin_data_migration_tests.
[cabot] out:  > cabotapp:0010_plugin_data_migration
[cabot] out: Error in migration: cabotapp:0010_plugin_data_migration
[cabot] out: Traceback (most recent call last):
[cabot] out:   File "manage.py", line 11, in <module>
[cabot] out:     execute_from_command_line(sys.argv)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
[cabot] out:     utility.execute()
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
[cabot] out:     self.fetch_command(subcommand).run_from_argv(self.argv)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
[cabot] out:     self.execute(*args, **options.__dict__)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
[cabot] out:     output = self.handle(*args, **options)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
[cabot] out:     ignore_ghosts = ignore_ghosts,
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/migration/__init__.py", line 220, in migrate_app
[cabot] out:     success = migrator.migrate_many(target, workplan, database)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 256, in migrate_many
[cabot] out:     result = migrator.__class__.migrate_many(migrator, target, migrations, database)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 331, in migrate_many
[cabot] out:     result = self.migrate(migration, database)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
[cabot] out:     result = self.run(migration, database)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 114, in run
[cabot] out:     return self.run_migration(migration, database)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 84, in run_migration
[cabot] out:     migration_function()
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
[cabot] out:     return (lambda: direction(orm))
[cabot] out:   File "/home/ubuntu/2015-02-18-db554a5/cabot/cabotapp/migrations/0010_plugin_data_migration.py", line 28, in forwards
[cabot] out:     polymorphic_ctype = orm['contenttypes.contenttype'].objects.get(model='hipchatalert'),
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
[cabot] out:     return self.get_queryset().get(*args, **kwargs)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
[cabot] out:     num = len(clone)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
[cabot] out:     self._fetch_all()
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
[cabot] out:     self._result_cache = list(self.iterator())
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
[cabot] out:     for row in compiler.results_iter():
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
[cabot] out:     for rows in self.execute_sql(MULTI):
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
[cabot] out:     cursor.execute(sql, params)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
[cabot] out:     return self.cursor.execute(sql, params)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
[cabot] out:     six.reraise(dj_exc_type, dj_exc_value, traceback)
[cabot] out:   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
[cabot] out:     return self.cursor.execute(sql, params)
[cabot] out: django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block
[cabot] out:

**Comment by candland** [comment]
Looks like I need the cabot_alert_hipchat plugin enabled. I removed it since we don't use hipchat, but adding it back to cont/production.env fixed the migration.

    # Plugins to be loaded at launch
    CABOT_PLUGINS_ENABLED=cabot_alert_hipchat,cabot_alert_twilio,cabot_alert_email

**Comment by bonniejools** [comment]
@candland At the moment we have hard dependencies on the default plugins in order to create a clear upgrade path for older installations. This dependency will hopefully removed in the future. Glad you sorted out your problem.
