### ISSUE TITLE
Actions in response to alerts

### ISSUE THREAD

**Issue by 0rc** [arachnys/cabot#194]
Would be great to have possibility to run a script (or http post or something like that) in response to new alert
Is there something like this in plans?
What do you think about this?

**Comment by dbuxton** [comment]
Now that the plugin architecture has landed this is pretty trivial - see https://github.com/bonniejools/cabot-alert-twilio for a pretty comprehensive (albeit not terribly well documented) example of how to write your own plugin.

**Comment by packetcollision** [comment]
This idea would be improved by the service-level config in #183
