### ISSUE TITLE
Cannot deploy on 12.04

### ISSUE THREAD

**Issue by trahma** [arachnys/cabot#196]
Hello, I'm experiencing issues deploying cabot.  After spending half my day yesterday on our openstack instances, I spawned a 12.04 (32bit and 64bit) ubuntu image on my digital ocean account and I'm still experiencing the same exact error.

```
[ubuntu@x.x.x.x] sudo: foreman run python manage.py syncdb -e conf/production.env
[ubuntu@x.x.x.x] out: Usage: manage.py syncdb [options]
[ubuntu@x.x.x.x] out:
[ubuntu@x.x.x.x] out: Create the database tables for all apps in INSTALLED_APPS whose tables haven't already been created, except those which use migrations.
[ubuntu@x.x.x.x] out:
[ubuntu@x.x.x.x] out: manage.py: error: no such option: -e
[ubuntu@x.x.x.x] out:


Fatal error: sudo() received nonzero return code 2 while executing!

Requested: foreman run python manage.py syncdb -e conf/production.env
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "cd /home/ubuntu/2015-03-20-8362690 && source /home/ubuntu/venv/bin/activate && foreman run python manage.py syncdb -e conf/production.env"

Aborting.
Disconnecting from x.x.x.x... done.
sudo() received nonzero return code 2 while executing!

Requested: foreman run python manage.py syncdb -e conf/production.env
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "cd /home/ubuntu/2015-03-20-8362690 && source /home/ubuntu/venv/bin/activate && foreman run python manage.py syncdb -e conf/production.env"
```

I'm not a python guy by any means so any help would be appreciated.

**Comment by packetcollision** [comment]
It looks like the version of foreman that's being run is passing the -e to manage.py rather than using it itself.

Can you run `foreman --version` and `python --version` so we can attempt to reproduce it?

**Comment by trahma** [comment]
Sure thing.. here you go:

ubuntu@cabot:~/2015-03-20-8362690/bin$ foreman --version
0.78.0
ubuntu@cabot:~/2015-03-20-8362690/bin$ python --version
Python 2.7.3

**Comment by tommiatplayfish** [comment]
Looks like I'm running into the same problem. Targetting the localhost. Funny thing is, this worked just fine a month ago or so. Ubuntu 14.04 on AWS.

[ubuntu@localhost] out: Usage: manage.py syncdb [options]
[ubuntu@localhost] out:
[ubuntu@localhost] out: Create the database tables for all apps in INSTALLED_APPS whose tables haven't already been created, except those which use migrations.
[ubuntu@localhost] out:
[ubuntu@localhost] out: manage.py: error: no such option: -e
[ubuntu@localhost] out:


Fatal error: sudo() received nonzero return code 2 while executing!

Requested: foreman run python manage.py syncdb -e conf/production.env
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c "cd /home/ubuntu/2015-03-30-2829eed && source /home/ubuntu/venv/bin/activate && foreman run python manage.py syncdb -e conf/production.env"

Aborting.

**Comment by tommiatplayfish** [comment]
So, fixed this by downgrading foreman

gem uninstall foreman
gem install foreman --version 0.77.0

Could have something to do with this commit on 0.78
https://github.com/ddollar/foreman/commit/bc44afcbf3dfba8cc11deb7db8df9b09c1c096ed

**Comment by trahma** [comment]
That resolved things on my end.  I'll leave this open for now assuming you'll want to resolve this.  If not feel free to close.
