### ISSUE TITLE
using api to create checks/instances/services ?

### ISSUE THREAD

**Issue by xinity** [arachnys/cabot#198]
back on track, 

we are working again on cabot integration, we were wondering if we can use the API's to create checks/instances/services ?

at first we though about using SQL query on postgresql, but APIs seem to be a better choice, still our first tests failed :(

**Comment by 0rc** [comment]
I am successfully using API to create checks, instances and services, so you can ask more specific questions if you have

**Comment by xinity** [comment]
@0rc how do you achieve that ? can you share some examples ?

i've tried through the webui but i've failed :(

FYI, i maybe a n00b at it , don't shoot :)

**Comment by 0rc** [comment]
It works just straightforward as described in documentation

**Comment by xinity** [comment]
Then i'm a real n00b because i've failed
