### ISSUE TITLE
remove configuration from os env

### ISSUE THREAD

**Issue by JackLeo** [arachnys/cabot#199]
Ok there is few points to this.
* it is not desirable to maintain system os vars. Cfg file is a usual way to go for all deployable systems. https://docs.python.org/2/library/configparser.html
* Plugins right now uses os env. They just should use django.settings, and settings should be populated by whatever means. E.g. Right now I did a clone of cabot and had edited settings.py but for plugins ether I have to clone them as well meaning each plugin effectively has it's own configurations.

I would be happy to contribute to this, but first of all I should know if you agree

**Comment by dbuxton** [comment]
Well we are essentially using a config file, it's just one that's automatically generated (via foreman). 

As you correctly point out, one major advantage of using os env is that plugins don't have to maintain their own configs or somehow get passed config by the main app - they can just read straight from the os.

I don't really have an ideological position on this but at Arachnys we are used to the pattern of using foreman to export config into the os and then grabbing it from there, so I'm reluctant to change unless there's a really strong reason.

**Comment by JackLeo** [comment]
If you are going to manual setup - foreman is yet another dependency that is unnecessary. Ether way it is a config file and instead of build in python config interpreter you are using third party solution.

Regards the plugins - they have to be installed in the same environment thus they can easily reach django settings. Once you trow out foreman out of the window - it becomes an annoyance.

All of this is on the point of wether to enforce others to use another dependency or not. It just makes it harder to deploy once you step out of your own internal company setup that is not the same anywhere else.

I understand your stance and it is justifiable, just I am expressing my views from different side of the fence :)

**Comment by dbuxton** [comment]
Completely understand and makes sense. I also agree about settings for plugins, that's not a big deal.

In terms of the practicalities of automating migrations and stuff though - how would you do that without using fabric? Surely at the end of the day you're going to end up with some external tool (ansible, chef, etc) doing the deployment/orchestration?

**Comment by JackLeo** [comment]
Yes, and thats up for the company to decide. Some use saltstack, some sheff, some fabric and they are all right.

You shouldn't also forget deamon management solutions. Equivalently different sys admins will use different solutions. Systemd, supervisor, init.d scripts they are as well correct solutions and here is the main point where configs in file become most important since the easier launch the simpler it is to integrate the tool to the stack.

To give some background, my setup is command and control machine with different software running on it. Each peace runs on separate user within virtualenv if possible and to manage deamons I am running supervisor. My supervisor config for cabot is:

```
[program:cabot-web]
directory=/home/cabot/cabot/
command=/home/cabot/virtual/bin/gunicorn -c gunicorn.conf cabot.wsgi:application
environment=PYTHON_EGG_CACHE="/home/cabot/.python-eggs",TWILIO_ACCOUNT_SID="<acc>",TWILIO_AUTH_TOKEN="<token>",TWILIO_OUTGOING_NUMBER="<number>"
autostart=true
autorestart=true
user=cabot

[program:cabot-worker]
directory=/home/cabot/cabot/
command=/home/cabot/virtual/bin/celery worker -B -A cabot --loglevel=INFO --concurrency=16 -Ofair
environment=PYTHON_EGG_CACHE="/home/cabot/.python-eggs",TWILIO_ACCOUNT_SID="<acc>",TWILIO_AUTH_TOKEN="<token>",TWILIO_OUTGOING_NUMBER="<number>"
autostart=true
autorestart=true
user=cabot

[group:cabot]
programs=cabot-web,cabot-worker
```

PYTHON_EGG_CACHE is some error I encountered for some reason during deployment, and did not investigated further

**Comment by packetcollision** [comment]
I agree with the stuff about getting rid of the foreman dependency, but I totally disagree with moving away from environment variables. 

Environment variables are the one thing that is consistent across different languages, so from an ops point of view, having them be the configuration language is very convenient. Environment variables are also the generally-accepted way to do configuration of Docker containers, so switching to something else would mean additional complexity in packaging Cabot inside a container.

**Comment by JackLeo** [comment]
Environment variables are also global values for OS. So essentially it's like using global arguments on method where you only need to pass few values. They are exposed on the entire shell level. If you don't want to expose those variables yet again you have to get out of the way of regular usage and do weird hoops for jailing those variables or having your config to be exported each time when you start the app.

If you are dropping foreman then just think how would you manage 2 instances of cabot on the same machine? I am not saying that is a must to have feature, but you are limiting your self, since all you could do is run cabot twice and pass different --setting param or equivalent.

And also if you would drop foreman - how you would reboot the machine? have those variables in .bashrc or where? Its again same config just in most random location possible.

Also what is not consistent about text files? Default format for Python config parser is exactly the same as plethora of other software (mysql, phpfmt from top of the head) since it uses ini format https://en.wikipedia.org/wiki/INI_file

**Comment by packetcollision** [comment]
The standard pattern for Debian/Ubuntu is to have a config file in /etc/default/*servicename* that contains the ENV variables. The init script simply sources the file. RedHat/CentOS have a similar paradigm but use /etc/sysconfig/*servicename*. Those files are only sourced by the init script for the associated services, so they do not pollute the general environment. It's simple, it's standard, and it doesn't require framework-specific knowledge to use.

**Comment by JackLeo** [comment]
OK let's look at those files for services in /etc/defaults/ on ubuntu 14.04.

Redis 2.8.4 - has nothing
Supervisor 3.0b2 - optional deamon settings (default nothing)
memcached 1.4.14 - if it's enabled (again just single setting and rest are in cfg's)
MySQL 5.5.41 - Not present
Graphite toolbox - Not present
php-fmt - Not present (not really a service though)
Jenkins - has actually settings there.

Please provide more examples of this you can, but from my viewings - it's rarely used pattern for non OS default services like cron.

I would not consider it to be framework specific, - it's language specific and why you would care? It's not like other program would read cabot settings and for python it's pretty standard, actually for Django python file is even more standard. manage.py even accepts --settings parameter, so you don't even need to implement anything.

Please provide some examples of python installable services that use this. Maybe I had seen to little, but I haven't encountered any at all.

Please don't take this offensively but I genuinely interested in this. I am trying to find some examples and the only thing that I found is https://celery.readthedocs.org/en/latest/tutorials/daemonizing.html#init-script-celeryd and with this everything points to that within /etc/defaults if you keep anything then it's your deamon settings and not project settings like twillio account details or postgres logins, granted with some exceptions.

Now back to /etc/defaults quite interesting article on that http://0pointer.de/blog/projects/on-etc-sysinit.html

**Comment by cmclaughlin** [comment]
Just wanted to give my opinion here - I just setup Cabot with SaltStack.  Didn't use the Fabfile at all.  Configuration via env vars was pretty nice as I was able to write them to /etc/sysconfig/supervisord, which is sourced from supervisord's init script.

**Comment by dbuxton** [comment]
I think we're moving towards docker as main development and deployment mechanism, so I don't think we're going to move towards a config file format. Thanks for the input though all.

In fact the env file format just **is** an .ini format without section headings so fairly interchangeable. The main difference is reading from local environment rather than a file.
