### ISSUE TITLE
Separate/cleanup deployment scripts from code base

### ISSUE THREAD

**Issue by JackLeo** [arachnys/cabot#200]
Package should be system agnostic. Deployment procedure should be done via pip/easy_ install and not fabric.

This reflects issue #118 as well. Good example of python system deployment is sentry project.

**Comment by dbuxton** [comment]
I agree with this to some extent but not sure how to handle things like `./manage.py collectstatic`, `./manage.py compress` in that situation. Not saying it can't be done, just easier to do in Fabric in my experience.

How does Sentry handle this sort of thing?

**Comment by JackLeo** [comment]
Manage can be quite simply wrapped in setup.py. 

From my experience all you need to do is to wrap manage.py contents in a method (lets say `main()`) and within setup.py add:

```
    entry_points = {
        "console_scripts": [
            "cabot = cabot.manage:main",
        ],
    },
```

this would create executable. Lets say within virtualenv - virtual/bin/cabot

hardest part would be to move gunicorn or equivalent wsgi handler, but again this is after a question if it is worth it or not.

**Comment by JeanFred** [comment]
We now distribute cabot as a pip package, and have removed Fabric/shell scripts. Closing this :)
