### ISSUE TITLE
Idea - management command for testing alerts.

### ISSUE THREAD

**Issue by JackLeo** [arachnys/cabot#201]
I am not exactly sure how to test if alerts are coming or not. I had some issues with email settings so I did test using shell and just ran django's send mail since that is what the plugin does.

However after those changes I got emails of missing api urls for some reason and not the alerts when I deliberately had changed a check so that it would fail on next instance. I am in processing of finding the issue, but the point is still the same.

It would be great to have a tool for sending out a test alert to a certain user from console or/and UI.

Maybe there is and I just had missed it, if so - sorry.

**Comment by grzegorz-dubicki** [comment]
I think is releted to #61.

**Comment by grzegorz-dubicki** [comment]
+1

**Comment by JeanFred** [comment]
Closed with #488
