### ISSUE TITLE
sending SMS or email for instance as well as services

### ISSUE THREAD

**Issue by xinity** [arachnys/cabot#204]
maybe dumb question but,

has we can send email/sms/call for services, i was wondering if we can do the same for instances ?

our goal is to separate instances and services alert , something like:
- instances alert goes to the Ops team
- services alert goes to the Dev team

any tips wwelcome :)

Regards,

**Comment by xinity** [comment]
all right seems my question was really dumb! sorry guys ! :(

i've taking a look at instance_detail.html.
i've seen this piece of code
 <h5>
        {% if instance.email_alert %}<i class="fa fa-envelope"></i> Email{% endif %}
        {% if instance.hipchat_alert %}<i class="fa fa-comment"></i> Hipchat{% endif %}
        {% if instance.sms_alert %}<i class="fa fa-mobile"></i> SMS{% endif %}
        {% if instance.telephone_alert %}<i class="fa fa-phone"></i> Telephone{% endif %}
 </h5>

which is related to the type of alert configured for instances.
what i can't understand is why in my case, i only have hipchat configured (without doing anything) .

did i miss something, is my cabot installation broken in some ways ?

**Comment by xinity** [comment]
after diging some in cabot and django admin pages.
i've found where i can add another alerting option.

i had to go to django admin --> instances --> [name of my instance] and add a tick on sms and email for example.

i think alerting option should be available through cabot itself, so we should not have to go through django admin.

i'll try something and make a quick and dirty PR to see if you guys are interested

**Comment by xinity** [comment]
@dbuxton as i'm digging, i can see that only service are available for sending_alert, i'd like to add instance as well, but this would need to update all cabot plugins :(

maybe you have a better idea ?

**Comment by xinity** [comment]
As far as i understand cabot everything regarding alerting has been wrapped around services, i haven't found a suitable solutions to have alerting as well for instances :-(

**Comment by xinity** [comment]
UPDATE: it is not related to cabot itself but with alerting plugins instead .
instance alert are correctly triggered, but for some unknown reason alerting plugin doesn't behave correctly @bonniejools any idea why a instance critical alert still send hipchat/email message as if it was from services ?

**Comment by dbuxton** [comment]
I suspect the instance system was never really engineered to work with
alerts. Should be easy enough to patch

**Comment by xinity** [comment]
@dbuxton That's what i've tried but i failed, any tips ?

**Comment by xinity** [comment]
I'll close this one and openup another more focused on what i'm trying to achieve. @dbuxton it doesn't sound that easy to patch sadly
