### ISSUE TITLE
stashboard plugin broken with latest cabot pull

### ISSUE THREAD

**Issue by xinity** [arachnys/cabot#205]
hi,

seems the stasboard plugin in broken , while deploying latest github code from cabot, here is what i have:
 File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/__init__.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth1_auth.py", line 10, in <module>
    from requests.utils import to_native_string
ImportError: cannot import name to_native_string

FYI python libs deployed:
Django==1.6.8
Markdown==2.5
MultiString==0.1.5
PyJWT==0.1.2
SOAPpy==0.12.22
South==1.0
XSLTools==0.5
amqp==1.3.3
anyjson==0.3.3
apt-xapian-index==0.45
argparse==1.2.1
billiard==3.3.0.13
cabot==0.0.1-dev
cabot-alert-email==1.3.1
cabot-alert-hipchat==1.6.1
cabot-alert-stashboard==0.1
cabot-alert-twilio==1.1.4
celery==3.1.7
chardet==2.0.1
d2to1==0.2.11
defusedxml==0.4.1
distribute==0.6.24
dj-database-url==0.2.2
django-appconf==0.6
django-celery==3.1.1
django-celery-with-redis==3.0
django-compressor==1.4
django-filter==0.7
django-jsonify==0.2.1
django-mptt==0.6.0
django-polymorphic==0.5.6
django-redis==1.4.5
django-smtp-ssl==1.0
djangorestframework==2.4.2
docutils==0.12
gevent==1.0.1
greenlet==0.4.5
gunicorn==18.0
hiredis==0.1.1
httplib2==0.7.7
icalendar==3.2
kombu==3.0.8
lxml==3.4.2
medusa==0.5.4
meld3==0.6.5
mock==1.0.1
oauthlib==0.7.2
ovh==0.3.3
psycogreen==1.0
psycopg2==2.5.1
python-apt==0.8.8.2
python-dateutil==2.1
python-debian==0.1.21
pytz==2014.10
redis==2.9.0
requests==0.14.2
requests-oauthlib==0.4.2
six==1.5.1
soaplib==2.0.0-beta2
supervisor==3.0a8
twilio==3.4.1
wsgiref==0.1.2
wstools==0.4.3

i've tried with request 2.X but i have another issue with cabot checks:
Error in performing check: 'instancemethod' object is not iterable

which seems to be related to this issue #30 

did i missed something ?

Regards,

**Comment by packetcollision** [comment]
As I said before, when you're having trouble with a plugin, please file a ticket against that plugin.

**Comment by xinity** [comment]
sorry i though i should post it here :)

my bad, will fix this

Regards
