### ISSUE TITLE
OpsGenie integration

### ISSUE THREAD

**Issue by dibits** [arachnys/cabot#219]
Hi, I developed an alert plugin for [OpsGenie](http://opsgenie.com) that you can see [here](https://github.com/dibits/cabot-alert-opsgenie).

The plugin works flawlessly when I'm in dev, but when I install it in my prod environment, the plugin doesn't appear as an option in the "alert" section for the services. Also checked that it doesn't appear in the django admin, but if I go to the "alert subscriptions" I can see there that users have the option to add the OpsGenie user/group.

Any ideas what could be the issue here or where to start debugging it?

Thanks!

**Comment by dbuxton** [comment]
Have you added in the `production.conf` file?

**Comment by dibits** [comment]
Yes, I assume you mean conf/production.env, which I did, I run the manage.py syncdb and restarted Cabot. Also added the plugin to the upstart scripts since those weren't updated. Maybe I need to re-deploy everything? Although that would kill the idea of "plugins". What it's weird for me is that worked without problems in the vagrant machine and also the configuration for the users appears. 
Seems like the plugin is half way there...

**Comment by dbuxton** [comment]
I assume it needs to be reprovisoned and redeployed, but hard to be sure.
Sounds like you are not using built in deployment scripts? If you manually
repeat what those are doing, what happens?

**Comment by dibits** [comment]
Just launched a new instance... (Ubuntu 14.04 on AWS)
`fab provision -H <host>`
`fab deploy -H <host>`

`production.env` has the opsgenie plugin enabled and the required configuration.
No errors, everything worked out of the box (not even the django-compressor error I was getting before) and I can see the opsgenie plugin was installed in the venv.
I create a new service and in the alert section opsgenie is not there. I go to the alert subscriptions and the option to configure opsgenie is there.

Destroyed my vagrant machine and recreated it (`vagrant destroy -f && vagrant up`), `development.env` has the opsgenie plugin configuration. 
`vagrant ssh`
`pip install cabot-alert-opsgenie`
`foreman run python manage.py syncdb --migrate`
`foreman start`

Login to Cabot, create a new service and the option to select the OpsGenie in the alert field is there. After configuration the plugin is working as expected. And that's even after changing the vagrant machine to run with the latest ubuntu 14.04...

Would it be too much to ask if you could review my code and see if I'm missing something maybe? 
Thanks in advance!

**Comment by dbuxton** [comment]
Very possibly is an error in Cabot itself

**Comment by dibits** [comment]
Any ideas where to look for it and/or what to look for? I'd be happy to help and contribute a PR.

**Comment by Dinoshauer** [comment]
Just had the same problem, it was the `.pyc` files that did it for me. Just remove them, they're evil :)

**Comment by dbuxton** [comment]
Closing this as fixed
