### ISSUE TITLE
No way to add plugin user data ?

### ISSUE THREAD

**Issue by romankor** [arachnys/cabot#224]
I just upgraded cabot yesterday after we have been using it for a year in the old system.

I had to wrap my head around for several hours to figure out why my UserProfiles. 
I do understand that have to a row in the alertpluginuserdata table for every old UserProfile ?
Then i have to have a row for every alertpluginuserdata in each of my plugins user data ?

![image](https://cloud.githubusercontent.com/assets/2689706/7949344/dbbfacea-0941-11e5-914d-dc9e3c216c8f.png)

It seems there is some bug in the UI that does not allow me to add then at all from the admin ?

When i press add new alert user data I get this screen :
![image](https://cloud.githubusercontent.com/assets/2689706/7949421/904d36b4-0942-11e5-8865-d800ea967a31.png)

Guys please help , wasted like 10 hours of work time on that already.

**Comment by cmclaughlin** [comment]
Hi,

I also noticed the plugin user data isn't exposed via the Django admin. However, you can access it like this:

https://cabot.shopstyleops.com/user/< USER PROFILE ID HERE >/profile/

**Comment by JeanFred** [comment]
@frankh fixed it in 245e871, released in 0.9.2
