### ISSUE TITLE
http://cabotapp.com/dev/contribute-code.html says "contact us" but doesn't provide information as to how

### ISSUE THREAD

**Issue by wolfsage** [arachnys/cabot#229]
On http://cabotapp.com/dev/contribute-code.html there's this block of text:

    If you have any questions about roadmap or plans, please contact us or file an issue on GitHub.

But I can't find contact information anywhere obvious for things like support requests etc.

Is there an IRC network? A mailing list? Or just github issues?

Thanks.

**Comment by dbuxton** [comment]
Issue is best, I will change the wording.
