### ISSUE TITLE
Make timeout decimal field

### ISSUE THREAD

**Issue by Melevir** [arachnys/cabot#23]
It's good idea to check speed of loading with cabot. 1 second is too much - more flexible scale is required here such as 100 ms and like that.
Since requests [support](http://docs.python-requests.org/en/latest/user/quickstart/#timeouts) non-integral timeouts all that should be done is migration of timeout to DecimalField and new 'help_text'.

**Comment by frankh** [comment]
While i can see the use of very short check timeouts, i think for 99.9% of use-cases, 1 second is short enough.

I can't see this being worth adding a migration. Please re-open if you feel strongly that this is necessary as it certainly could be done
