### ISSUE TITLE
`raw_data` is not escaped correctly when included in HTML (potential XSS)

### ISSUE THREAD

**Issue by JordanMilne** [arachnys/cabot#231]
See https://github.com/arachnys/cabot/blob/a03450507f8cabd44d4c7120d1bd6cde7ee3f4c5/cabot/templates/cabotapp/statuscheckresult_detail.html#L34. Since [`raw_data` contains data that may be partially user-controller](https://github.com/arachnys/cabot/blob/a03450507f8cabd44d4c7120d1bd6cde7ee3f4c5/cabot/cabotapp/models.py#L717), XSS may be possible.

Simple repro: Add an HTTP watch on http://saynotolinux.com/tests/cabot/escaping.txt with a text match on "somethingelse". Upon the first check failure, navigate to the page for that check and an `alert()` box will be shown.

Easy way around that, only embed `raw_data` in the JS if it actually contains JSON. You should also guard against JSON containing embedded `</script>` tags ([like this](http://saynotolinux.com/tests/cabot/escaping.json)) by replacing `<` and `>` with their unicode escape equivalents (`\u003C` and `\u003E` respectively) before running the json through `|safe`.

**Comment by imnotjames** [comment]
Alright - I've opened a pull request which should fix this issue, and I tested it against both of the reproducible examples you had.
