### ISSUE TITLE
Cabot over SSL (HTTPS)

### ISSUE THREAD

**Issue by grzegorz-dubicki** [arachnys/cabot#233]
How to configure that? Is it documented in some non-obvious place?

**Comment by dbuxton** [comment]
There's a commented out bit in the `setup_dependencies.sh` script which will do:

https://github.com/arachnys/cabot/blob/f5f201ca925556cba9204308825af3c1b85b6f9a/bin/setup_dependencies.sh#L159

HTH - please close if so

**Comment by grzegorz-dubicki** [comment]
Notes to self/others reading this:

```setup_dependencies.sh``` script is run only once, when installing Cabot, so nginx configuration is not being overwritten by Cabot reconfiguration (redeploy). Therefore its easiest to add HTTPS support by just editing nginx config on the running Cabot machine.

Anyway its resolved for me, thank you @dbuxton . :)
