### ISSUE TITLE
Monitoring by script feature.

### ISSUE THREAD

**Issue by skorokithakis** [arachnys/cabot#235]
Is there a way to add script monitoring? Rather than watch Jenkins/Graphite/HTTP, I would like to have Cabot run a script every time it wants to make a check, and if the script exits cleanly, it means the service is fine, otherwise an alert is generated.

This would make it very easy for me to add whatever custom check I wanted without having to run Jenkins or Graphite, and I would also be able to write complex checks like "make sure authentication works for user demo".

**Comment by dbuxton** [comment]
It's something we've thought about (and I think I may even have seen a pull request for it) but it's not something that for our internal use case Cabot would handle - rather we would run these sorts of scheduled long-runnning checks on Jenkins and watch the output of those jobs with Cabot.

Jenkins is just a lot better at all the bumph around error handling, scheduling, farming out execution to slaves, provisioning, and building that into Cabot seems like overkill to me.
