### ISSUE TITLE
Why does the Check's API requires "name" when editing? 

### ISSUE THREAD

**Issue by lghamie** [arachnys/cabot#236]
Trying to edit a Graphite check through the API, i send a PUT like this:
```
PUT /api/graphite_checks/8/ HTTP/1.1
Host: localhost:8089
Accept-Encoding: gzip, deflate
Authorization: Basic ZG9ja2VyOmRvY2tlcg==
User-Agent: node-superagent/1.2.0
Content-Type: application/json
Content-Length: 11
Connection: close

{"value":9}
```

and I get 
```
HTTP/1.1 400 BAD REQUEST
Server: nginx/1.4.6 (Ubuntu)
Date: Fri, 24 Jul 2015 13:11:08 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Accept
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS

25
{"name": ["This field is required."]}
0
```

Obviously, adding the "name" field makes it work, but  I was wandering if it's really necessary, being that the id "8" should be enough to identify the record I want to update.

To close the issue I'd like to know if there's a way to make it optional.

**Comment by dbuxton** [comment]
Strictly you should be using `PATCH` - can you try that?

**Comment by lghamie** [comment]
Works!

Closing
