### ISSUE TITLE
Creating users via API?

### ISSUE THREAD

**Issue by lghamie** [arachnys/cabot#237]
Probably django noob question, but, on the api I cant find a way to add or edit users, I can only see this endpoints:
```
{
    "alertplugins": "http://localhost:8089/api/alertplugins/",
    "instances": "http://localhost:8089/api/instances/",
    "status_checks": "http://localhost:8089/api/status_checks/",
    "icmp_checks": "http://localhost:8089/api/icmp_checks/",
    "shifts": "http://localhost:8089/api/shifts/",
    "http_checks": "http://localhost:8089/api/http_checks/",
    "services": "http://localhost:8089/api/services/",
    "jenkins_checks": "http://localhost:8089/api/jenkins_checks/",
    "graphite_checks": "http://localhost:8089/api/graphite_checks/"
}
```
I can see the django admin app, which POSTs to this URL to create new users
```
/admin/auth/user/add
```
But the format is not a regular JSON, which is what I would need.

Any ideas on how to create users via a RESTful api?

Thanks for the great work guys!

**Comment by lghamie** [comment]
So I forked and uncommented the lines that provide this functionality, I guess that's the way.

**Comment by thomasleveil** [comment]
Since caa4bb5 (May 18, 2016), you can use the environment variable `EXPOSE_USER_API` to control if the user* endpoints should be exposed on the rest api.
