### ISSUE TITLE
PagerDuty integration?

### ISSUE THREAD

**Issue by Zeelot** [arachnys/cabot#240]
I don't quite see how cabot is a replacement for PagerDuty (as the readme suggests). I am mostly interested in using cabot to detect failures through graphite but send the alerts through PagerDuty since PD allows me to manage the on call scheduled and contact preferences as well as being the central point for this configuration (allowing me to alert people through many things along with cabot checks).

Is it possible to allow PagerDuty to be another alerting system for cabot?

**Comment by dbuxton** [comment]
If you're already using PD with all its features Cabot isn't going to replace it; but if you don't have it, Cabot has the basic functionality to set up on-call rotas and manage alerts.

It would be easy to write an alerting plugin for pagerduty - look at https://github.com/bonniejools/cabot-alert-hipchat for example. There's in fact one out there already: see https://github.com/Affirm/cabot-alert-pagerduty/

**Comment by Zeelot** [comment]
Aha, excellent. Thanks for the feedback.
