### ISSUE TITLE
Add headers to HTTP checks

### ISSUE THREAD

**Issue by iurisilvio** [arachnys/cabot#242]
I want to make an HTTP call to one ip with a host header.

Route53 health checks have this option.

**Comment by dbuxton** [comment]
Sounds like a reasonable need, I don't think we're likely to add but if another contributor would like to I would certainly be up for including.

**Comment by iurisilvio** [comment]
I started using cabot yesterday and this feature can be really useful for
me.

I'll try to send a pull request with this feature in next days.

Thanks!
