### ISSUE TITLE
Templated HTTP Checks?

### ISSUE THREAD

**Issue by wstiern** [arachnys/cabot#244]
Hi, we have say 50 servers that all do the same thing that we want to configure the same HTTP check for -- it looks like when configuring a HTTP check, Cabot expects a full URL string. Is it not able to append the hostname to the URL?

For example, we want to check ":8080/status" on every server of the same flavor. How would we go about configuring that? Documentation seems non-specific on this particular subject. Thanks in advance!

**Comment by dbuxton** [comment]
At the moment what you want to do isn't easily possible. I'd suggest using the API to configure this automatically - presumably if you are configuring 50 servers you must already be doing auto configuration...

**Comment by wstiern** [comment]
Thanks for your quick reply. We look forward to watching Cabot mature as a monitoring platform. :)
