### ISSUE TITLE
how to make cabot running with latest python requests version ?

### ISSUE THREAD

**Issue by xinity** [arachnys/cabot#256]
hy,

we are working several cabot plugins (hopefully some of them will be available publicly on github).
for one of our module, we uses ovh python client : https://github.com/ovh/python-ovh

this module needs requests 2.7.0 , but cabot uses requests 0.14.2.
we have tried latest requests version but failed because of some changes in resp.json handling.

how can it be possible to make cabot perfectly running with latest requests version ?

Thanks for your help,

Regards

**Comment by dbuxton** [comment]
All that needs to be done is:

1. Update requests version in [setup.py](https://github.com/arachnys/cabot/blob/5d454976878c3ac8fd2b95e2c7ad594e15c6f88d/setup.py)
2. Grep through the code to replace all instances of `resp.json` with `resp.json()`

We're not using anything fancy in requests so I think that should be OK. Comments welcome

**Comment by xinity** [comment]
It seems to be working, needs a little more test to be sure everything is ok :)

i'll keep you in touch with a nice (or so i hope) PR, when i'm sure everything works right

**Comment by dbuxton** [comment]
I actually fixed this in f587076 - if there are any other changes please send a PR...
