### ISSUE TITLE
memory leak with celery with big production system ?

### ISSUE THREAD

**Issue by xinity** [arachnys/cabot#257]
hi all,

we have figured out that our production system is eating memory as the days goes by !
after a little dig in, we seems to have found the culprit which seems to be celery itself.

our platform starts 16 celery process , log level ERROR 
we have around 300 checks (graphite, http ....)
The production server has 32go RAM and is a quad-core Xeon previous generation.

does anyone have seen some issues like ours ?

we are searching what would make celery eats all servers memory, any clues very very appreciated :)

Thanks a lot,

Regards,

**Comment by dbuxton** [comment]
There are lots of efficiencies to be made in general, but a hacky way is to set `CELERYD_MAX_TASKS_PER_CHILD` http://celery.readthedocs.org/en/latest/userguide/workers.html#max-tasks-per-child-setting - that will just mean that each worker will get killed after executing (say) 100 tasks. It doesn't fix the leak but it does stop it becoming a killer. Let me know how you get on.

**Comment by xinity** [comment]
i've modified cabot/celeryconfig.py to add : 
CELERYD_MAX_TASKS_PER_CHILD = '20'

this has drastically reduced our memory usage!

nice!

**Comment by dbuxton** [comment]
Good, you can probably afford a bit more (100s at least) but YMMV. Will close.
