### ISSUE TITLE
how to activate a newly installed plugin with an already cabot installation running ?

### ISSUE THREAD

**Issue by xinity** [arachnys/cabot#258]
hy,

we have worked on several plugins and as they are working perfectly on our dev plateform (using vagrant), we haven't been successfull activating it on an already running production platform, even restarting cabot doesn't make the newly deployed plugin available in services alert drop down list.

have we missed something ? should we recreate postgresql DB from scratch ?

Thanks for your clues :)

**Comment by onagorodniuk** [comment]
Hi, 
did you added new plugin in ./conf/production.env in 
CABOT_PLUGINS_ENABLED=cabot_alert_hipchat==1.6.1 ... ?

**Comment by dbuxton** [comment]
Also bear in mind that if you are using default deployment mechanism, env changes will not be reflected by just editing files on the server and restarting - you need to run the full deployment. (The env is exported by foreman)

**Comment by xinity** [comment]
we are using our own system (docker based) will PR soon if interested :)
i'll double check if i haven't miss anything

**Comment by dbuxton** [comment]
Will presume closed

**Comment by xinity** [comment]
not really closed, same thing happened, what's strange is on my dev platform (sqlite) everything is fine, on production (postgresql DB), i can't make my custom plugins available while i can see tables created, some aren't populated correctly like alertplugins , alertplugins_id_seq ....

seems to be why i can't use my plugins, but i can't figure out how to fix :(

**Comment by nobe4** [comment]
Same issue here, I found a way to manually activate the plugin through the `psql` shell. I share here what I found, in case it can help @xinity. (tested on a digitalocean droplet, created after the quick-start guide).

If you want to try it on your configuration, you have to add a  line on the table `cabotapp_alertplugin` and on the `cabot_alert_your_plugin_pluginname`.

   $ sudo -u postgres psql
   postgres=# \connect index

The `cabotapp_alertplugin` table lists the activated plugin, so you should add yours with the following command: 

     index=# INSERT INTO cabotapp_alertplugin (polymorphic_ctype_id, title, enabled) VALUES (XX, 'name', 't');

Note that you must replace `XX` with the next `polymorphic_ctype_id` integer.

Next, your table will look like:

```
 id | polymorphic_ctype_id |       title       | enabled
----+----------------------+-------------------+---------
  1 |                    9 | Hipchat           | t
  2 |                   11 | Twilio Phone Call | t
  3 |                   12 | Twilio SMS        | t
  4 |                   14 | Email             | t
  5 |                   15 | name              | t
```

Finally you can add your newly created id (here: `5`) to your plugin's table: 

    index=# INSERT INTO cabot_alert_your_plugin_pluginname (alertplugin_ptr_id) VALUES (5);

Result:
 
```
index=# SELECT * FROM cabot_alert_your_plugin_pluginname;
 alertplugin_ptr_id
--------------------
                  5
(1 row)
```

And there you go, those dirty changes gave me access back to my plugin. 
Hope it will help.
