### ISSUE TITLE
Graphite checks passing when they shouldn't be

### ISSUE THREAD

**Issue by crucial7** [arachnys/cabot#260]
I found that the following line of code has a bug, https://github.com/arachnys/cabot/blob/master/cabot/cabotapp/models.py#L629, doesn't check for None correctly. Which causes a [Metric] [Check type] [Value] failure in the check to pass through as successful when it wasn't. I have changed that line of code to the following, https://github.com/crucial7/cabot/blob/master/cabot/cabotapp/models.py#L629.

I have created a pull request for this problem.

Great app by way and thanks for the hard work on this!

**Comment by dbuxton** [comment]
Thanks for spotting this

**Comment by crucial7** [comment]
No problem at all. Let me know if my pull request looks ok or not.

**Comment by JeanFred** [comment]
This was fixed by #261 then?

**Comment by dbuxton** [comment]
Closing as fixed @crucial7 - let me know if not the case
