### ISSUE TITLE
Graphite output only deals with the latest change and not the entire data series

### ISSUE THREAD

**Issue by crucial7** [arachnys/cabot#262]
I might be understanding this incorrectly, but I did have some debug statements and it shows that the min, max, and avg to be the same value.

The line in question is: https://github.com/arachnys/cabot/blob/master/cabot/cabotapp/models.py#L603 the variable 
```javascript
graphite_output['series']
```` 
is always only showing one data point which is the latest data point. Is this by design or a bug?

If it is a bug I have a fix for it. I also added checks for < (avg), > (avg), <= (avg), and >= (avg). Let me know your thoughts.

**Comment by dbuxton** [comment]
Sounds like a bug, but I'm not sure I totally understand. Do you have a test case that shows what you mean?

**Comment by crucial7** [comment]
Sure, I was thrown off by the average, min, and max calculations that are
in
https://github.com/arachnys/cabot/blob/master/cabot/cabotapp/graphite.py#L85-L87
also
the min vs max checks in
https://github.com/arachnys/cabot/blob/master/cabot/cabotapp/models.py#L603-L627
those
two made me think that it's supposed to work with the entire series rather
than just the latest.

As an example if you have the following series:

[[20.3, 1442834740], [12.5, 1442834750], [0.1, 1442834760], [0.8,
1442834770], [134.9, 1442834780], [151.0, 1442834790]]

you will have the average = 151.0, min = 151.0, and max = 151.0. Rather
than what I thought as average = 53.3, min = 0.1, and max = 151.0.

**Comment by dbuxton** [comment]
@crucial7 if you look at the tests I added in ee34cee I think you'll find that it's working correctly - or am I missing something?

Can you check and re-open this issue if you think there is a bug?
