### ISSUE TITLE
Error Performing Check min/max

### ISSUE THREAD

**Issue by chriscannon** [arachnys/cabot#265]
Hello,

I did a fresh install of Cabot on a brand new EC2 Ubuntu 14.04 image and I'm getting a failed status on the check whenever I set a graphite check where the check type is set to anything other than "Equal to" (e.g., "Greater than", "Less than", etc.).

When I set the check type to be something with "Greater than" I get this error:
`Error in performing check: max` and the raw data is `None`

When I set the check type to be something with "Less than" I get this error:
`Error in performing check: min` and the raw data is `None`

I can tell it can properly connects to my Graphite server because when I set the check type to "Equal to" it returns valid JSON in the raw data and passes the check.

Any ideas about what's going on? Do I need a certain version of Graphite to properly work with Cabot? Is there any known issues with Cabot and Ubuntu 14.04?

Thanks,
Chris

**Comment by dbuxton** [comment]
Sounds like a regression to me. I have a long flight in front of me so may write a few tests...

**Comment by chriscannon** [comment]
Is there any way I can see what request is being made to the graphite server so that I can make sure it's response is correct?

**Comment by dbuxton** [comment]
This should be fixed by 257bc4a - can you give it a try and see what happens?

It was only affecting scenarios where there was more than one series coming back from the server but at least one of the series being returned was all `[null, ..., null]`

Let me know how you get on and reopen this if you continue to have problems.

**Comment by chriscannon** [comment]
Works now, thanks!
