### ISSUE TITLE
acknowledgment, tweaking idea

### ISSUE THREAD

**Issue by xinity** [arachnys/cabot#267]
hi,

been playing with the acknowledgment recently build into cabot.
awesome work by the way :)

i think it would be neat to have the ack stat in the services page, so we can ack or re-enable alert a bit easier :)

as well as the possibility to choose duration of the acknowledgment in the config file :)

ready to contribute if needed

**Comment by dbuxton** [comment]
Do you mean on the main dashboard? That would be very easy, just add a link (see https://github.com/arachnys/cabot/blob/fc33c9859a6c249f8821c88eb8506ebcad645a50/cabot/templates/cabotapp/service_detail.html#L20)

You can already set duration in the config file - see https://github.com/arachnys/cabot/blob/45449861503fdfc3a8dee04180803a3c057c505a/cabot/cabot_config.py#L30

**Comment by xinity** [comment]
dashboard updated :)
