### ISSUE TITLE
How to find the host from which Cabot was deployed?

### ISSUE THREAD

**Issue by grzegorz-dubicki** [arachnys/cabot#270]
Hi,

I have an embarassing problem: I forgot which server did I use to deploy one of my Cabot instances...

Can I find out the the host that was used for deployment in any way?

**Comment by dbuxton** [comment]
Have you tried `history | grep "fab deploy"`?

**Comment by grzegorz-dubicki** [comment]
Thanks, but the thing is that I don't know on which host (and as which user) should I run this command.

Doest deployed Cabot store any deployment log where I would find this information? (IP would be enough)

**Comment by dbuxton** [comment]
But presumably you deployed it from your local machine or CI server? That's where you would run this...

**Comment by grzegorz-dubicki** [comment]
I haven't found the server in the end but I have just cloned Cabot repot again, checked out the commit of my Cabot deploy, copied ```production.env``` from it the and re-deployed it according to http://cabotapp.com/use/configuration.html and everything runs smoothly now. :)
