### ISSUE TITLE
Allow non-embed links for recovery instructions

### ISSUE THREAD

**Issue by blysik** [arachnys/cabot#273]
Every company has their own style of wikis, with pages that can generally be reached via generic https urls.  

If recovery instructions could just be generic links, it would allow teams considering Cabot to leverage existing wiki documentation.

**Comment by dbuxton** [comment]
Yes don't see why not. Originally I think we were a bit worried about embedding arbitrary information but in fact there's probably not even a big problem just allowing iframe embed of wiki pages

**Comment by carande** [comment]
I would be interested in this; particularly for supporting google docs
