### ISSUE TITLE
checks running more frequently than they should be (dupes)

### ISSUE THREAD

**Issue by blysik** [arachnys/cabot#274]
I have an installation of Cabot in a heroku-like system.  Things are going well.  However, I notice that checks are firing more frequently than they should.  Here's a screenshot:

![screen shot 2015-10-16 at 11 47 16 am](https://cloud.githubusercontent.com/assets/58610/10550449/d0808f00-73fb-11e5-89c3-112c290d1ebc.png)

This appears to be happening for all types of checks.

Where should I start looking for troubleshooting this?  Thanks!

**Comment by dbuxton** [comment]
I'd guess for some reason you had a number of checks scheduled and not running, and now they have all started running at once. See if they get back to normal in time, or flush your redis database...

**Comment by blysik** [comment]
> keys *
1) "unacked_index"
2) "_kombu.binding.celeryev"
3) "_kombu.binding.celery"
4) "_kombu.binding.celery.pidbox"
5) "unacked"

Safe to just flushdb?

**Comment by blysik** [comment]
Could the problem be that I'm running too many celery worker instances?  I had though I could, but now I'm reading about celery and I'm not sure.  I'm launching 4 instances of:
```
celery worker -B -A cabot --loglevel=INFO --concurrency=2 -Ofair
```

**Comment by blysik** [comment]
Aha.  Found it.
```
-B, --beat
Also run the celery beat periodic task scheduler. Please note that there must only be one instance of this service.
```
Obviously I'm starting 4 of those too.  Sigh.  Fixing.  Thanks.

**Comment by blysik** [comment]
Closing.
