### ISSUE TITLE
access django command-line utilities?

### ISSUE THREAD

**Issue by carande** [arachnys/cabot#275]
I was able to get Cabot installed and working, and set up several services and checks for my system.  All of this was done using a single user.  Embarrassingly, I then set this user to "inactive", which has served to fully lock me out of the app - I can't log into ANY Django Admin pages...

Redeploying Cabot did not have any effect. 

I was wondering if there is a way to access the django user information on the host machine running cabot directly?  I was hoping to simply create a new django superuser, and then log in with that.  I tired `python manage.py createsuperuser` on both the ubuntu server running cabot as well as the machine I deployed cabot from, but it seems like manage.py was not able to access the same environment that cabot is running in:

`  File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'CELERY_BROKER_URL'
`

Is there a way to directly add a Django user to a Cabot instance?  Or another possible solution?  I'd prefer not to start over.

Thanks very much for any advice, I'm really liking Cabot so far!

**Comment by dbuxton** [comment]
You need to just use the same environment as you are running on production - so something like `foreman run ./manage.py createsuperuser -e conf/production.env` should work.

**Comment by dbuxton** [comment]
Going to close this but please re-open if you think there's a bug anywhere.

**Comment by carande** [comment]
Thanks very much!  I ended up doing a fresh install but it's good to realize where I was going wrong with my previous approach.
