### ISSUE TITLE
[question] use api to create an instance with default icmp check?

### ISSUE THREAD

**Issue by blysik** [arachnys/cabot#284]
Is there a way, via the API, to create an instance with the default icmp check?  Or do I need to do something like:

* create icmp check, and keep status_check id
* create instance, and associate it with the previously created status_check

Thanks!

**Comment by blysik** [comment]
That's how I ended up doing it, if any is interested

* create the icmp_check, get the id
* create the instance with the the id above in the status_checks array

**Comment by dbuxton** [comment]
I think this is a reasonably common API usage idiom, if you think we should be doing something different please feel free to reopen.
