### ISSUE TITLE
Sending alerts when graphite server is not availible

### ISSUE THREAD

**Issue by evgenyidf** [arachnys/cabot#287]
Cabot sending tons of alerts when graphite server is unavailable or authentication has been failed.
It should send one information email and stop alerting per each check..

**Comment by dbuxton** [comment]
I agree that this can be annoying but it's difficult to know how big an issue no information is for you. 

Do you have a proposal of what sort of notification you'd like to get? What about frequency? What if there's a general outage that kills your graphite machine as well as your whole infrastructure? Wouldn't you want to be notified?

Genuine question - for us this would be a critical issue and so we don't mind too many alerts (especially with the acknowledgement mechanism that recently landed) but would like to establish parameters around this.

**Comment by evgenyidf** [comment]
I think that such alert emails should be sent to "administrator" but not to every single user which run graphite check ..

**Comment by dbuxton** [comment]
I think if the services Cabot is monitoring are mission-critical then a failure to be able to check if the services are working should itself be considered a critical failure... What you are describing wouldn't work for us, for example.

If you were to submit a PR for some ability to configure this I'd be happy to review and in theory to merge, but I don't think we should change this globally.

**Comment by dbuxton** [comment]
Closing this. The "official" workaround is to set up an HTTP check for graphite being up, and base your reaction on that. If you have a very specific solution I'd be happy to reopen.
