### ISSUE TITLE
Delete instance API call 

### ISSUE THREAD

**Issue by iliyanotlioneberia** [arachnys/cabot#288]
Currently Cabot only supports display and create instances etc. but I am interested in using the api to delete too. Now is this something that Cabot is not utilising for a reason or it is just not being added yet?

**Comment by dbuxton** [comment]
Please feel free to add

**Comment by NickBeeuwsaert** [comment]
I've been able to execute a HTTP `DELETE` on instances to delete them, (e.g. `DELETE http://cabot.example.com/api/instances/6`)

**Comment by AvihayTsayeg** [comment]
I've been able to execute a HTTP DELETE as well

**Comment by dbuxton** [comment]
Sounds like this can be closed @iliyanotlioneberia ?

**Comment by iliyanotlioneberia** [comment]
Well I guess we can close that, I ended up extending cabot in order to make a delete request. It feels like I am not doing it right if you guys can do it.

**Comment by iliyanotlioneberia** [comment]
Just curious - did anyone use requests to perform delete? (I get 403 - Forbidden)

**Comment by AvihayTsayeg** [comment]
Here is some code did at Kenshoo,
it is tailored to our purpose, but can be used in general.

[cabot_entity.py.txt](https://github.com/arachnys/cabot/files/59367/cabot_entity.py.txt)
[service.py.txt](https://github.com/arachnys/cabot/files/59368/service.py.txt)
[http_check.py.txt](https://github.com/arachnys/cabot/files/59370/http_check.py.txt)
[graphite_check.py.txt](https://github.com/arachnys/cabot/files/59369/graphite_check.py.txt)
[entities_operations.py.txt](https://github.com/arachnys/cabot/files/59371/entities_operations.py.txt)
[__init__.py.txt](https://github.com/arachnys/cabot/files/59372/__init__.py.txt)

**Comment by AvihayTsayeg** [comment]
@iliyanotlioneberia was the code helpful ?

**Comment by iliyanotlioneberia** [comment]
I didn't have much time to review it yet to be honest, but I appreciate that you share these with me! I will have a look, and will update this post.

**Comment by AvihayTsayeg** [comment]
The problem was with your command was that you need to add / at the end **http://cabot.example.com/api/instances/6/**
and not 
http://cabot.example.com/api/instances/6

**Comment by iliyanotlioneberia** [comment]
you were right, the slash was the issue! thanks for that and for the scripts too!
