### ISSUE TITLE
Is PostgreSQL mandatory?

### ISSUE THREAD

**Issue by arikfr** [arachnys/cabot#29]
PostgreSQL is being installed as part of the dependencies by your setup fabric. I was wondering if there is any PostgreSQL specific feature you're using, or I can use MySQL just the same?

**Comment by JackLeo** [comment]
It works for me to. Some of the last migrations however tries to do something nasty, thus while running initial migrations - faking is an option (syncdb should generate equivalent db if south did not change the functionality since django 1.2)

**Comment by n3storm** [comment]
Is there a high risk of concurrency problems when using sqlite for less than 10 servers, around 20 services?

Thanks

**Comment by toabi** [comment]
@n3storm did you try it? I'm thinking about the same setup…

**Comment by zkendall** [comment]
Yeah, that'd be dope if SQLite could be used..

**Comment by seanvree** [comment]
Is there any update to this?  Can this still be run on MySQL?  Haven't seen any updated info?

THX

**Comment by iPalash** [comment]
Yes, I am running it with MySQL as the DB backend. You would need to install mariadb as well the python library 'mysqlclient' and configure the DB URL properly in default.env.

**Comment by seanvree** [comment]
@iPalash -  so am I just replacing PostgreSQL with Mariadb in order to use MySQL?
