### ISSUE TITLE
Support to send events to PagerDuty / Webhook-based consumers

### ISSUE THREAD

**Issue by unquietwiki** [arachnys/cabot#295]
https://developer.pagerduty.com/documentation/code

There's been an explosion of services using HTTP + JSON to feed event systems. It should be trivial to add support for PagerDuty (or other webhook service).

**Comment by dbuxton** [comment]
Does this work for you?

Generic webhooks would be nice too

**Comment by unquietwiki** [comment]
Hey, sorry for the late reply. I haven't had a chance to test that yet: I plan to dig into this more in January, and I was asking some folks on Reddit that know Python better than I to take a look as well.

**Comment by dbuxton** [comment]
OK I will close this for the time being but let me know if you want me to reopen.
