### ISSUE TITLE
Get status of services via API

### ISSUE THREAD

**Issue by jeroenmoors** [arachnys/cabot#297]
Hi,

I'm working on a dashboard that would also display a summary of our Cabot monitoring.

The API should be the way to go, but after playing with it for some time I can't find a call that returns the current status of our services? Am I missing something or is this feature just not available?

Thank you for your feedback!

Jeroen

**Comment by xinity** [comment]
depending on what you're looking for:
you can grab the information needed through this endpoint:
`http://[my cabot host]/api/status_checks/ `

example:
```
{
        "name": "my_check", 
        "active": true, 
        "importance": "ERROR", 
        "frequency": 5, 
        "debounce": 2, 
        "calculated_status": "passing", <== LOOK HERE
        "id": 787
    }, 
```

or this api endpoint:
` http://[my cabot host]/api/services/ `

example:
```
 {
        "name": "my_services", 
        "users_to_notify": [
            3, 
            4, 
            5, 
            6
        ], 
        "alerts_enabled": true, 
        "status_checks": [
            790, 
            789, 
            792, 
            791, 
            787, 
            788
        ], 
        "alerts": [
            1, 
            4
        ], 
        "hackpad_id": "", 
        "url": "[my hostname]", 
        "instances": [], 
        "overall_status": "PASSING",  <== LOOK HERE
        "id": 132
    }, 
```

a bit of json parsing should fullfill your needs :)

hoping this helps,

**Comment by jeroenmoors** [comment]
Thanks for you fast response!

We were not running the latest version. A simple git pull added the calculated_status field!
