### ISSUE TITLE
Problem with cron job of restarting cabot periodically

### ISSUE THREAD

**Issue by changbl** [arachnys/cabot#313]
Hi All, 

I am trying to setup a cron job to restart cabot-web and caob-celery services every some time (e.g., daily). However, this does not seem to work. I guess there is some problem with cabot upstart scripts in /etc/init/cabot* . Can someone help?

My cron job looks like (as root user)

* * * * * * /usr/sbin/service cabot-web restart
* * * * * * /usr/sbin/service cabot-celery restart

**Comment by dbuxton** [comment]
I think it should be just `/usr/sbin/service cabot restart`?

Haven't checked but I think the whole service is just called `cabot`

Reopen if that doesn't work

**Comment by changbl** [comment]
I tried `/usr/sbin/service cabot restart`. It is equivalent to restarting both cabot-web and cabot-celery.

However, it does not work when it is put in cronjob.

**Comment by changbl** [comment]
Btw, I am not able to reopen this issue. It was not closed by me.

**Comment by dbuxton** [comment]
I don't think this is a problem with cabot, rather with permissions (maybe)?
