### ISSUE TITLE
Issues with Let's Encrypt certificates

### ISSUE THREAD

**Issue by erral** [arachnys/cabot#317]
Hi:

We are using cabot to monitor our sites, and we have one them that has a SSL certificate obtained using Let's Encrypt. Since we enabled the certificate, cabot can't get the site status because it thinks that the certificate is not valid. The relevant error is:

> Request error occurred: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

So I entered manually in the virtualenv, and updated the requests library, forcing the install of the [security] extra: 

> $ pip install --upgrade requests[security]

And now the alert is gone.

Perhaps the version of requests library required by cabot could be updated (currently it requires requests==2.7.0 and the 2.9.1 version is already out. Moreover the [security] extras should also be installed (which is present from requests 2.4.1) and provides additional security checks when making connections.

By the way, thank you for this excelent tool. This connected with the telegram plugin ( https://github.com/codesyntax/cabot_alert_telegram) makes our lives easier :wink:

**Comment by dbuxton** [comment]
Sounds like an easy fix - just bump the version in `setup.py`. Will do in a PR and assuming tests pass, will merge.

**Comment by erral** [comment]
Thx!!!

**Comment by pabl0rg** [comment]
Hi, I am still having this problem, despite setup.py specifying requests 2.9.1

It seems to be a python problem on the server running cabot.  Can we use python 3 to run cabot?  Should that be in the fabric provisioning task?

https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning

**Comment by dbuxton** [comment]
Have you tried installing PyOpenSSL?

**Comment by pabl0rg** [comment]
Thanks for replying.  I had not tried it (did not know it existed).  

It worked.

**Comment by pabl0rg** [comment]
PS. another solution that also worked is using the cert with full chain from letsencrypt

**Comment by dbuxton** [comment]
Good to know...
