### ISSUE TITLE
[Feature Request] RSS Check

### ISSUE THREAD

**Issue by dustinchilson** [arachnys/cabot#319]
I'd like to read RSS Feeds for alerts from Cloud providers to send an alert if there's a upstream error.

ex
https://azure.microsoft.com/en-us/status/
http://status.aws.amazon.com/
https://status.cloud.google.com/
https://status.heroku.com/

**Comment by dbuxton** [comment]
We already do this on our instance using HTTP checks against the page itself - not sure what the RSS feed adds?

It's also possible to do this for alerting when specific text **is** on the page if necessary. (We use this for a few things but it's not common enough for us to bake in as a feature)

**Comment by dustinchilson** [comment]
We could regex the page looking for the error section when it's there. The regex on the azure page would be gross. I could regex the rss feed itself to find the event info. I had not thought to try that.

This could be a great use of #187.

**Comment by dbuxton** [comment]
Agree it would be great to get #187 actually done...
