### ISSUE TITLE
Make cabot URL configurable for reverse proxy

### ISSUE THREAD

**Issue by RomanKisilenko** [arachnys/cabot#321]
I would like to run cabot behind reverse proxy. I configure it to be available via /cabot/ URL. However it redirects to /services/ when I try to access it. 

Is there any way to configure URL prefix for cabot?

**Comment by dbuxton** [comment]
At the moment, not out of the box.

I would just do something like http://stackoverflow.com/a/20998131

**Comment by imnotjames** [comment]
so after trying to replace the `urls.py` via uwsgi aliases - or even manually updating a local branch - I found there are a few other cases where that method fails to work.

I created a pull request which fixes the few issues I had found, and adds in an environment variable for it. However, I'm not sure how long it will take to get reviewed and merged in given my lack of experience with django.  You can always grab the patch from that and apply it if you need it right away.
