### ISSUE TITLE
Documentation is missing HIPCHAT_URL

### ISSUE THREAD

**Issue by marvinthepa** [arachnys/cabot#339]
Although the Hipchat Plugin checks for HIPCHAT_URL (https://github.com/bonniejools/cabot-alert-hipchat/blob/master/cabot_alert_hipchat/models.py#L73), this is not mentioned in the documentation:

http://cabotapp.com/use/configuration.html#hipchat-alerting

I would have sent a pull request for the documentation, but I did not find it on github..

**Comment by JeanFred** [comment]
Good catch @marvinthepa! The documentation is in the gh-pages branch − see https://github.com/arachnys/cabot/blob/gh-pages/_posts/2014-01-08-configuration.md

I’d be happy to merge your PR :)

**Comment by marvinthepa** [comment]
There you go.
