### ISSUE TITLE
Upgrade Django to >=1.8

### ISSUE THREAD

**Issue by markunsworth** [arachnys/cabot#345]
Cabot is currently running on Django 1.6 which has been unsupported since April 1, 2015, Django 1.7 is also now out of support.

I've started a fork to try and do this but having some issues around the changes to the migrations process (using Django's own migrations instead of South), has anyone else had any success in doing this?

**Comment by dbuxton** [comment]
Seems like this would be addressed by the monster that is #349 ...

@JeanFred any thoughts?

**Comment by rewolf** [comment]
@markunsworth Did you ever start any work on this?

**Comment by markunsworth** [comment]
Only what is in that commit, I was hoping (and praying) that #349 would make it's way in to master. Looks like that has blocked due to the size though, so may need to be revisited. 

I'm unlikely to find the time or impetus to work on it any time soon though as we're mainly using the new Grafana plugin and alerting system now.

**Comment by JeanFred** [comment]
@rewolf Yes, #349 was just too big to be easily reviewable. We may be able to dedicate some resources internally to upgrade Django but can’t make any commitments just now. I’ll keep that issue updated. Thanks for your patience and your interest!

**Comment by frankh** [comment]
Since 0.8.0 cabot is on django 1.8
