### ISSUE TITLE
Deployment fails on 12.04 container

### ISSUE THREAD

**Issue by hiniko** [arachnys/cabot#348]
Hello,

I have been trying to install cabot on a 12.04 Ubuntu container running on a Debian Jessie host.

The Provision step works without issue but the deployment step fails. I am not too sure how to proceed in a sane way, I don't use python to this level personally. Any ideas?

```
[ubuntu@monitor] sudo: foreman run -e conf/production.env /home/ubuntu/venv/bin/pip install --editable /home/ubuntu/2016-05-15-3270540 --exists-action=w
[ubuntu@monitor] out: Traceback (most recent call last):
[ubuntu@monitor] out:   File "/home/ubuntu/venv/bin/pip", line 5, in <module>
[ubuntu@monitor] out:     from pkg_resources import load_entry_point
[ubuntu@monitor] out: ImportError: No module named pkg_resources
[ubuntu@monitor] out:
```

**Comment by dbuxton** [comment]
Sounds like an issue with setuptools, we should move to docker to eliminate weird issues like this...

**Comment by surfacescan** [comment]
Same thing happening here.

**Comment by aolgin** [comment]
Here as well when I tried a few days ago.

**Comment by surfacescan** [comment]
I used this docker-compose process and it worked great: https://github.com/shoonoise/cabot-docker

**Comment by Cohedrin** [comment]
Same here, went back through the commits until I could get a working deploy, first commit that successfully built was https://github.com/arachnys/cabot/commit/d8a54fd6f258a8c8516d01334cdcb5ace91b94b0

**Comment by niko-niko** [comment]
I will give the docker-compose a try thanks for linking it. 

Please consider having this wonderful looking application be able to deployed in a manual fashion as well as anything else you provide. 

I appreciate the connivence of using tools like fabric and docker as a form of making provisioning, deployment, packaging and provisioning easier tasks (depending on which you are focusing on). However it can be a pain when you may not want to use or can't use some of those tools in your environment.

**Comment by Wirzi** [comment]
still getting this error...
anything new regarding this problem?

**Comment by koriaf** [comment]
If you get this problem you can solve like that:
```
ssh ubuntu@...
cd /home/ubuntu/venv
sudo chown ubuntu -R .
source ./bin/activate
wget https://bootstrap.pypa.io/ez_setup.py -O - | python
```

virtualenv will be installed again. It's like python/ubuntu bug and I don't think fabfile can do much about it.

**Comment by mattvonrocketstein** [comment]
I ran into the setuptools problem also, and changing the fabfile to use "virtualenv --setuptools" fixed it.    This change (amongst other stuff) is in my open pull-request here https://github.com/arachnys/cabot/pull/353/files

**Comment by Wirzi** [comment]
Thanks that worked! 👍

**Comment by niko-niko** [comment]
Thanks! That also worked for me! Would be great to see the pull request fix
this.

On 29 June 2016 at 18:38, Colin Wirz <notifications@github.com> wrote:

> Thanks that worked! 👍
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/arachnys/cabot/issues/348#issuecomment-229431206>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA7BqvRVSnNgm99IQ36-QHLy4QxLM6Eyks5qQq2PgaJpZM4Ie40f>
> .
>



-- 
Sherman Rose

Web     : shermanrose.uk
Twitter : hiniko
Skype   : hiniko-niko
Tel     : 07795 901 183
PGP Key : 0xDEC30FF45C823F58
PGP Sig : 5F71 3308 20AB 5E5C 2B63 4D1A DEC3 0FF4 5C82 3F58

**Comment by JeanFred** [comment]
#353 was merged ; and more generally installing should be more straightforward using either pip or the docker-compose setup. I’m closing this but feel free to reopen if you encounter issues.

(Note: we should officially deprecate the Fabfiles and bash scripts)
