### ISSUE TITLE
"exclude" commands not displayed in Graphite check previews or results logs (display issue only)

### ISSUE THREAD

**Issue by saday-cimpress** [arachnys/cabot#351]
I set up a bunch of alerts last week that had "exclude" in the metric text.  However, when I look at the history of check results, the "exclude" commands are all stripped out.  We have 1 specific metric that skews data quite drastically and sets off a lot of false alarms and just "exclude" it in other reporting tools, but Cabot seems to strip these out for some reason.

Graphite doc reference: http://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.exclude

I couldn't find anything in the docs about this being intentional.  We're modifying our data to accommodate this, but it'd be nice for Cabot to behave the same as our other graphite-based tooling.

**Comment by dbuxton** [comment]
Hmm. Cabot doesn't do any transformation as far as I can tell:

https://github.com/arachnys/cabot/blob/32705404275903efc94258199ee06ea112c138f3/cabot/cabotapp/models.py#L640

... calls ...

https://github.com/arachnys/cabot/blob/8a4b3710d5d318674fe3d5f1caa739bbdaadb698/cabot/cabotapp/graphite.py#L55

Maybe an issue (version?) with your graphite server? If you make the request directly, what do you get?

**Comment by saday-cimpress** [comment]
If I make the request directly it works fine (in Grafana and other tools, as well as graphite directly).  
![image](https://cloud.githubusercontent.com/assets/19539443/15681876/1931f3f2-2729-11e6-9de8-188a04331977.png)

The issue is visible here: "excludes" in the statement, but not in the result log.  The dozen false alarms I got over the long weekend prove out that the excludes are not being used.

We're running a build from this commit:
https://github.com/arachnys/cabot/commit/d8a54fd6f258a8c8516d01334cdcb5ace91b94b0

**Comment by dbuxton** [comment]
@saday-cimpress and you've verified that this is actually happening with the real checks (as opposed to the preview)? i.e. on https://$SERVER/result/$ID/

**Comment by saday-cimpress** [comment]
It _claims_ to be happening with the real checks.  Working with the graphite server owner today to validate what is being sent - I will post again if we can get an answer.

![image](https://cloud.githubusercontent.com/assets/19539443/15682535/24b2751e-272c-11e6-8332-11338a215067.png)

**Comment by saday-cimpress** [comment]
Interesting, the graphite server logs show the "exclude" even though Cabot logs do not.  I'll followup again this afternoon after we poke at it a bit more.  This may just be a display issue in Cabot and not a functional bug.

**Comment by saday-cimpress** [comment]
So after a lot of digging, our _data_ problem boiled down to a Graphite order of operations thing.  We reproduced it in other tooling.  However, Cabot has a display bug that "exclude" functions are not displayed as part of the query text in the preview or results screens.  Graphite may be stripping the exclude statements due to order of operations logic internal to Graphite, though, which is an entirely different story.

I'll update the issue title to reflect that this is a display issue.

**Comment by dbuxton** [comment]
It still seems like this might be a problem with Graphite not Cabot? Can you verify that it's the latter?

(There simply isn't any evaluation of the JSON returned so I don't know where the `exclude` **could** be getting stripped)

**Comment by saday-cimpress** [comment]
Well whoever is stripping it is doing it above the graphite log level.  The graphite logs have the excludes, the Cabot logs do not.

Feel free to close the issue, I guess, if you're confident it's not Cabot.

**Comment by dbuxton** [comment]
Happy to reopen in the future
