### ISSUE TITLE
Wrong status on graphite checks

### ISSUE THREAD

**Issue by erez-rabih** [arachnys/cabot#352]
Hi,

I am trying to create a graphite alert for high cpu usage on hosts.
The metric name is host.*.cpu
When I put the metric with the \* I get success even when one of the hosts has a higher cpu value than the threshold I've set.

When I put the specific name of the host in the metric name as in host.host-01.cpu the check fails as expected.

Am I using the graphite checks wrong here?

Thanks.

**Comment by erez-rabih** [comment]
I have had a look on the docs there it say that if any datapoint makes the fail condition true then the check should be true but I'm seeing a repetitive behaviour in which the check status is decided only by the last point of each series.

**Comment by erez-rabih** [comment]
I ended up using the Graphite summarize function on max value for each series.
This way even if the last value passes the check the check fails if it had any point above the threshold within the timerange

**Comment by dbuxton** [comment]
Thanks for posting this. It could be that this is tolerating one failing check but it would be good to have a bit more information to debug. Can you paste in the raw JSON output from the graphite check that was passing when it should have failed? Maybe also take a screenshot of the check config?

**Comment by erez-rabih** [comment]
The JSON output of the graphite check:
```
[{"target": "stats.gauges.kubernetes.deployments.mailman.missingPods", "datapoints": [[0.0, 1465452000], [0.0, 1465452005], [0.0, 1465452010], [0.0, 1465452015], [0.0, 1465452020], [0.0, 1465452025], [0.0, 1465452030], [0.0, 1465452035], [0.0, 1465452040], [0.0, 1465452045], [0.0, 1465452050], [0.0, 1465452055], [0.0, 1465452060], [0.0, 1465452065], [0.0, 1465452070], [0.0, 1465452075], [0.0, 1465452080], [0.0, 1465452085], [0.0, 1465452090], [0.0, 1465452095], [0.0, 1465452100], [0.0, 1465452105], [0.0, 1465452110], [0.0, 1465452115], [0.0, 1465452120], [0.0, 1465452125], [0.0, 1465452130], [0.0, 1465452135], [0.0, 1465452140], [0.0, 1465452145], [0.0, 1465452150], [0.0, 1465452155], [0.0, 1465452160], [0.0, 1465452165], [0.0, 1465452170], [0.0, 1465452175], [0.0, 1465452180], [0.0, 1465452185], [0.0, 1465452190], [0.0, 1465452195], [0.0, 1465452200], [0.0, 1465452205], [0.0, 1465452210], [0.0, 1465452215], [0.0, 1465452220], [0.0, 1465452225], [0.0, 1465452230], [0.0, 1465452235], [0.0, 1465452240], [0.0, 1465452245], [0.0, 1465452250], [0.0, 1465452255], [0.0, 1465452260], [0.0, 1465452265], [0.0, 1465452270], [0.0, 1465452275], [0.0, 1465452280], [0.0, 1465452285], [0.0, 1465452290], [0.0, 1465452295], [0.0, 1465452300], [0.0, 1465452305], [0.0, 1465452310], [0.0, 1465452315], [0.0, 1465452320], [0.0, 1465452325], [0.0, 1465452330], [0.0, 1465452335], [0.0, 1465452340], [0.0, 1465452345], [0.0, 1465452350], [0.0, 1465452355], [0.0, 1465452360], [0.0, 1465452365], [0.0, 1465452370], [0.0, 1465452375], [0.0, 1465452380], [0.0, 1465452385], [0.0, 1465452390], [0.0, 1465452395], [0.0, 1465452400], [0.0, 1465452405], [0.0, 1465452410], [0.0, 1465452415], [0.0, 1465452420], [0.0, 1465452425], [0.0, 1465452430], [0.0, 1465452435], [0.0, 1465452440], [0.0, 1465452445], [0.0, 1465452450], [0.0, 1465452455], [0.0, 1465452460], [0.0, 1465452465], [0.0, 1465452470], [0.0, 1465452475], [2.0, 1465452480], [2.0, 1465452485], [2.0, 1465452490], [2.0, 1465452495], [2.0, 1465452500], [2.0, 1465452505], [2.0, 1465452510], [2.0, 1465452515], [2.0, 1465452520], [2.0, 1465452525], [2.0, 1465452530], [2.0, 1465452535], [0.0, 1465452540], [0.0, 1465452545], [0.0, 1465452550], [0.0, 1465452555], [0.0, 1465452560], [0.0, 1465452565], [0.0, 1465452570], [0.0, 1465452575], [0.0, 1465452580], [0.0, 1465452585], [0.0, 1465452590], [0.0, 1465452595]]}]
```

The check config metric is `stats.gauges.kubernetes.deployments.mailman.missingPods`
screenshot:
![image](https://cloud.githubusercontent.com/assets/813024/15920385/343d95e8-2e22-11e6-8626-098cd6640adf.png)

Clearly there are points greater than 0 in the datapoint set but still the check passes.

**Comment by rmrf** [comment]
@dbuxton will this commit merge into master branch?

**Comment by frankh** [comment]
The commit is now merged, please re-open if it hasn't resolved this issue
