### ISSUE TITLE
email alerts not sending

### ISSUE THREAD

**Issue by lnyuan** [arachnys/cabot#356]
I was able to successfully get my graphite data into cabot and tested cases to make sure it would fail, but I'm not getting any emails. I have configured everything in production.env and am seeing results in the cabot app, but no email alerts are being sent.

**Comment by dbuxton** [comment]
Who/what are you using as your SMTP provider? Out of the box Cabot is set up for Amazon SES which is a bit of an unusual choice, you may need to play with the `SES_BACKEND` environment variable (see  https://github.com/arachnys/cabot/blob/master/cabot/settings.py#L147)

**Comment by dbuxton** [comment]
See also https://github.com/arachnys/cabot/issues/217

**Comment by lnyuan** [comment]
I am now able to get emails telling me that my alerts are back to normal, but am not getting anything when they fail. I tried 3 different graphite checks with warning, error, and critical settings and still am not getting anything except when the checks go back to normal. 

Do you know what may be the issue with this?

**Comment by dbuxton** [comment]
Well it's not your email config... 

You should make sure that the alerts are passing before they fail. Otherwise I'm not sure what's wrong here, sorry.

**Comment by lnyuan** [comment]
I think I figured it out. Thanks though!

**Comment by ssuda** [comment]
Hi, 
  It is not sending any emails for amazon ses, @lnyuan how did you solve this.
