### ISSUE TITLE
obtain old data for check

### ISSUE THREAD

**Issue by lnyuan** [arachnys/cabot#357]
Is there anyway to write a check that uses data from the previous week and compares it to current data? 

Further, it seems that the check is only able to obtain data from the past 10 minutes. I tried to change GRAPHITE_FROM from -10min to -60min but it appears that it still only looks at data from the past 10 minutes.

**Comment by dbuxton** [comment]
You can do this using `timeShift` in graphite. See https://github.com/arachnys/cabot/issues/51 for example.

I'm not sure about the `GRAPHITE_FROM` issue.

**Comment by lnyuan** [comment]
What exactly does GRAPHITE_FROM do? My understanding is that it is used to change how far back to look for the data? 

My data is hourly and gets published on the fifth minute of each hour, but it seems that if any check is performed after the tenth minute of the hour and fails, cabot won't trigger an alert. Further, if I were to change the frequency of the check to 60 minutes, it increments by a minute every hour, which messes up my check since my window frame to collect data is so small.

**Comment by dbuxton** [comment]
OK, looking at it, it is passed through to Graphite: see https://github.com/arachnys/cabot/blob/8a4b3710d5d318674fe3d5f1caa739bbdaadb698/cabot/cabotapp/graphite.py#L18

However the whole window may not be used when determining whether the check succeeds or fails. **That's** (confusingly) specified by the `mins_to_check` argument to `parse_metric`, which is supplied by `Check.frequency` (see https://github.com/arachnys/cabot/blob/32705404275903efc94258199ee06ea112c138f3/cabot/cabotapp/models.py#L640)

Complicating this further is that graphite's data frequency may or may not correspond to an actual minute. 

Probably this code needs to be readdressed and I know that a few people have proposed solutions. Both #127 and #139 wholly or partially address this. However it just hasn't been a priority on our end.

@JeanFred is this something we should look at (finally) fixing? Interested in your thoughts.

**Comment by dbuxton** [comment]
This should be fixed by #366 - @lnyuan can you have a look and see if this resolves your issue?

**Comment by erez-rabih** [comment]
Hi,
I recently pulled master from the cabot repository and now my GRAPHITE_FROM settings does not effect the actual from query parameter on the graphite checks.
It makes cabot graphite checks unusable for me since the default last 10 minutes is not enough for me. Any workaround this?

**Comment by newtechfellas** [comment]
Is there a solution to this?
