### ISSUE TITLE
SSL certificate check fails

### ISSUE THREAD

**Issue by Wirzi** [arachnys/cabot#358]
I have a domain gourmendo.com and a subdomain api.gourmendo.com.
The check for the ssl certificate on gourmendo.com is ok but the one for api.gourmendo.com fails.

Error message: **Request error occurred: hostname 'api.gourmendo.com' doesn't match 'gourmendo.com'**

I have created one "Let's Encrypt" certificate for both of the domains. Is this maybe the problem?

**Comment by dbuxton** [comment]
This is to do with SNI support in Python < 2.7.9: see http://docs.python-requests.org/en/master/community/faq/#what-are-hostname-doesn-t-match-errors

Moving to a more predictable docker-based setup will help solve this issue but it's not really a bug in Cabot so much as a deployment challenge. Going to close accordingly.
