### ISSUE TITLE
Password Reset Emails coming from webmaster@localhost

### ISSUE THREAD

**Issue by markunsworth** [arachnys/cabot#360]
_(I'll get around to submitting a pull request on this - but here as a reference for other users)_

When trying to send password reset emails they are being sent by webmaster@localhost. 

This causes SES email sending to fail, unless you add them to the list of senders (which isn't actually possible as you need to click a link in a confirmation email for addresses you add in the SES UI)

Most straightforward fix is to set [`DEFAULT_FROM_EMAIL`](https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-DEFAULT_FROM_EMAIL) in the settings.py 

The most obvious email address to use  (IMO) is the `CABOT_FROM_EMAIL`, which we set in the _environment_.env file

**Comment by dbuxton** [comment]
Good spot @markunsworth , this would be good to get a fix for
