### ISSUE TITLE
parse_metric not taking all data

### ISSUE THREAD

**Issue by zacharya19** [arachnys/cabot#367]
Is there a reason why on prese metric the for of the series values taking only the mins_to_check?
Because the datapoint are second so basically, if the default is 5 the function has 5 min of data - 300 datapoints, but on the series it will save only 5 seconds.

https://github.com/arachnys/cabot/blob/master/cabot/cabotapp/graphite.py#L81

**Comment by dbuxton** [comment]
There is a PR in there to address this: https://github.com/arachnys/cabot/pull/366

I'm waiting on @JeanFred for review.

**Comment by zacharya19** [comment]
Great!
I fixed it localy but wanted to make sure if there is a reason or I should open a pull request here, thanks!
