### ISSUE TITLE
No Django account prompted to be created

### ISSUE THREAD

**Issue by ethandrower** [arachnys/cabot#373]
Hi all,

While running the outlined instructions,  the deployment succeeds and launches cabot, but no where am I prompted to create a django admin account like suggested in the documentation.  Any help would be greatly appreciated!

> Deploy to the provisioned server:
> 
> $ fab deploy -H ubuntu@your.server.hostname
> # NB using `ubuntu` not `root` as above
> # Will prompt you to create a Django superuser which you'll use to log in via web and create additional users.

**Comment by mattvonrocketstein** [comment]
Use a command like this to add your superuser:

    fab -H user@host create_user:"username,email,password"

This issue needs some documentation.  It started working this way when deploy was changed to used "syncb --noinput" during bootstrap, beginning with [this PR](https://github.com/arachnys/cabot/pull/353).  Code for fabric command is [here](https://github.com/arachnys/cabot/blob/master/fabfile.py#L58)

**Comment by ethandrower** [comment]
Excellent, thank you for the code reference!

**Comment by levibostian** [comment]
@mattvonrocketstein I was also not instructed to create a Django superuser. I am viewing the login screen right now for cabot and have no idea what to enter for login creds. 

I entered `fab -H root@111.111.111.1111 create_user:"ubuntu,foo@mydomain.com,itypedpasswordhere"` as you instructed. Command run successfully. No luck.

**Comment by ethandrower** [comment]
Check to make sure the ordering is correct.  It's possible that the username/password fields are supposed to be flipped.   Try logging in with different combos of the three fields you passed to the create_user.   I'm not sure this is the problem but I think I remember discovering that the ordering of the parameters was incorrect.

**Comment by levibostian** [comment]
Yup. Thank you @ethandrower. As you sent that, I figured that out. https://github.com/arachnys/cabot/blob/master/fabfile.py#L58 specifies that create_user parameters are username,password,email. Indeed email/password in my command need to be flipped.

**Comment by JeanFred** [comment]
Good to see things resolved! Do you think we need to amend the documentation somewhere to make it clearer?  :)

**Comment by mattvonrocketstein** [comment]
Indeed but where to amend it?  Adding it to the github README is simple enough but not sure how to change http://cabotapp.com/use/deployment.html.  Also not clear on how fabfile-based deployment fits in with the docker-compose stuff that's been worked on lately

**Comment by JeanFred** [comment]
@mattvonrocketstein 
> Indeed but where to amend it? Adding it to the github README is simple enough but not sure how to change http://cabotapp.com/use/deployment.html.

That website lives in the `gh-pages` branch − see https://github.com/arachnys/cabot/blob/gh-pages/_posts/2014-01-08-deployment.md

> Also not clear on how fabfile-based deployment fits in with the docker-compose stuff that's been worked on lately

We are definitely looking into moving towards docker-compose based deployments, indeed.

**Comment by mattvonrocketstein** [comment]
Does moving towards docker-compose deployments make the fabric stuff obsolete?

**Comment by dbuxton** [comment]
@mattvonrocketstein it will eventually, but we may want to keep Fabric around for some ad-hoc tasks within containers.

**Comment by mattvonrocketstein** [comment]
I will update documentation to the places mentioned later today and submit a PR

**Comment by JeanFred** [comment]
Thanks @mattvonrocketstein ! Will review your PR quickly then :)
