### ISSUE TITLE
[feature] use instance and service names in checks as variables

### ISSUE THREAD

**Issue by jbrinegar** [arachnys/cabot#374]
I have applications that are deployed using the exactly same configuration, but in multiple physical locations.

Example:
service: eastcoast
service: westcoast
service: eurozone

It would greatly simplify my use of cabot if I could have these checks:
graphite check: prod.appname.$SERVICE.component.metric  
graphite check: prod.appname.$SERVICE.other_component.other_metric
http check: https://$SERVICE.company.com

Then these checks could easily be re-used across multiple services.

**Comment by rkalicinski** [comment]
I propose to make it more flexible by introducing tags for services. Tags could be used in check queries as variables: $deployment.appname.$service.other_component.other_metric
