### ISSUE TITLE
send alert when agent do not send metric a long time

### ISSUE THREAD

**Issue by lamhaison** [arachnys/cabot#382]
I want to have a feature like that because of some server can't check ping (block icmp rule). If you using icmp check you're wrong when monitor up down of server.
How to do that?.
Thanks

**Comment by dbuxton** [comment]
If I correctly understand your question: you want to use the absence of reporting of a metric to Graphite as a substitute for a ping check?

I think this is really a graphite question - I don't know off the top of my head if there's a way of checking for the last time a metric was reported but if there is, then I'd assume it's possible to report on it.

@JeanFred do you know off the top of your head?

**Comment by JeanFred** [comment]
@dbuxton I *think*  this is actually the default behaviour − setting a check on random Graphite hosts metric, with a « Expected hosts » of 1 should do the trick. (Assuming this is a metric that 
Of course, there could be other reasons for Graphite metric empty than the server being down (`Collectd` or whatever collection daemon could have crashed; there could be smth up with Graphite/Carbon itself…

**Comment by dbuxton** [comment]
OK @lamhaison can I close this and if you work it out would you post here?
