### ISSUE TITLE
Deploy with ansible

### ISSUE THREAD

**Issue by tuwid** [arachnys/cabot#393]
Any ansible playbooks laying around that you wanna share ?
I can write one for you but I'm not very sure on how to deploy this and would be something to nice to have

**Comment by JeanFred** [comment]
Hi @tuwid,

We do not have one at Arachnys (although we are heavy Ansible users!) ; and we probably won’t make one now that we are moving towards docker-compose for deployment.

However, I would certainly be happy that such a playbook exists and to review it if needed. I would not mind linking to it somewhere  from the Cabot docs too.

**Comment by JeanFred** [comment]
@tuwid There is now an Ansible role : https://github.com/cabotapp/ansible-cabot

**Comment by tuwid** [comment]
thanks, will test it

**Comment by frankh** [comment]
I'm going to close this issue, please re-open an issue in cabotapp/ansible-cabot if you have any issues
