### ISSUE TITLE
Twilio alerts not working

### ISSUE THREAD

**Issue by hajzso** [arachnys/cabot#395]
I configured cabot according to the documentation. SID and Auth key are correct, and I have outgoing number set to a freshly bought number. I have a service with Twilio Voice alerts enabled on it, with Critical status. I never get a call :( Do I have to do anything on the Twilio Console, apart from buying a voice capable number?

I had duty rota disabled until now, just tried adding one but I get 'no shifts downloaded' on the shifts page. Could this be a problem? Is there a guide on setting up shifts?

I don't get any twilio related errors in celery-1.log or web-1.log if that's where I should get them.

**Comment by rkalicinski** [comment]
AFAIR when I was doing some tests with Twilio, the duty rota had to be enabled. So yes, that might be the problem.

**Comment by hajzso** [comment]
I've just got duty rota to work, I am on duty and I still don't get calls. I have the feeling that I have to configure the number I want to use in some way in the Twilio Console. I bought the number and haven't touched it, it has the default settings.

**Comment by hajzso** [comment]
Alright, got it working. The problem was I didn't have permission to place international calls. If anyone runs into the same problem, I got this error:
`Error making twilio phone call: HTTP ERROR 400: 21215: Account not authorized to call +36305830161. Perhaps you need to enable some international permissions: https://www.twilio.com/user/account/settings/international`

Use the URL above to request it.
