### ISSUE TITLE
List on stackshare.io

### ISSUE THREAD

**Issue by weaktyper** [arachnys/cabot#397]
Nice tool. Simplicity of this tool is great. Perhaps, it should be highlighted on [stackshare.io](https://stackshare.io/)

**Comment by JeanFred** [comment]
@weaktyper Why not. I just submitted Cabot there, let’s see what they say. Thanks for the suggestion!

**Comment by stephenmoloney** [comment]
Nice. 👍  I'll give it a star. :star:

BTW, Is there a plugin to collect all the logs and present them in a graph?

**Comment by weaktyper** [comment]
Nice. 👍  I'll give it a star. :star:

BTW, Is there a plugin to collect all the logs and present them in a graph?
