### ISSUE TITLE
Check frequency is not working as expected

### ISSUE THREAD

**Issue by yuribit** [arachnys/cabot#398]
Hi,
I setup a check to run every 5 minutes but this is what is happening:

![screen shot 2016-12-08 at 4 33 56 pm](https://cloud.githubusercontent.com/assets/1260900/21033312/45ebb4d8-bd64-11e6-9c52-4f9cc5cf5395.png)

Sometimes the check is performed every 7 minutes, sometimes every 6 or twice the same minute (at 11:17pm). 

Am I the only one experiencing this behavior? Could it be related with some misconfiguration of Cabot?

**Comment by rkalicinski** [comment]
No, you are not the only one with such issue: https://github.com/arachnys/cabot/issues/368

**Comment by JeanFred** [comment]
Off the top of my head, could it be general load and Celery cannot keep up with too many tasks ?

**Comment by rkalicinski** [comment]
Yeah, that might be the reason. That's why the workaround with taking last execution time into account with next check is enough for me.

**Comment by yuribit** [comment]
I don't think the issue is related with the application load, I can reproduce the same issue having just one check in my Cabot instance.

**Comment by frankh** [comment]
I think I figured this out, it's because we have multiple celery beat services instead of just one. Making a PR now

**Comment by frankh** [comment]
Fix for this should be merged. Let me know if you still have issues

(see the docs for updating to the latest version)

**Comment by yuribit** [comment]
@frankh are you sure? I think it's not working because you guys are adding a random amount of time between each check... https://github.com/arachnys/cabot/blob/master/cabot/cabotapp/tasks.py#L45

**Comment by frankh** [comment]
@yuribit that would explain checks being +/- 1 minute off, not several minutes off (e.g. the 2 checks firing in the same minute)

I think point of that delay is to prevent very spiky cpu loads, although i'm not sure how effective it is
