### ISSUE TITLE
No email is being sent

### ISSUE THREAD

**Issue by tjosten** [arachnys/cabot#4]
I set up cabot and put my correct SES user information in the production config file. However, the app does not send any emails when a check fails. I checked both the SNS log and my mailserver log - the email is never sent.
I also made sure ever checkbox saying e.g. "enable notification" is checked.

**Comment by jaihind213** [comment]
hi i am unable to send email via aws ses.
but smtp gmail works.

here is my config. kindly help
---
EMAIL_USER='.....'
EMAIL_PASSWORD='....'
EMAIL_BACKEND='django_smtp_ssl.SSLEmailBackend'
SES_HOST=email-smtp.us-west-2.amazonaws.com
SES_PORT=465
SES_USE_TLS=True
---
i get the error 'Could not send Email alert: No module named 'django_smtp_ssl'

**Comment by dbuxton** [comment]
@jaihind213 good question, it looks like plugins are not currently installing their own dependencies in setup.py so I guess you'll have to do manually into the docker image.

@JeanFred is there a reason plugins are not responsible for their dependencies?

**Comment by jaihind213** [comment]
thanks @dbuxton . will try. i found something else.

so i removed 'django_smtp_ssl.SSLEmailBackend'  and i got error 'Could not send Email alert: Connection unexpectedly closed'

EMAIL_USER='.....'
EMAIL_PASSWORD='....'
SES_HOST=email-smtp.us-west-2.amazonaws.com
SES_PORT=465
SES_USE_TLS=True

with port 465 - a telnet from inside the docker image to  email-smtp.us-west-2.amazonaws.com HANGS

but with port 587 , a telnet from inside the docker image to  email-smtp.us-west-2.amazonaws.com works ...

**Comment by dbuxton** [comment]
Have you tried using `SES_PORT=587`?

**Comment by jaihind213** [comment]
ya. i have been actually fighting with different combos and both dont work (i got gmail working though on 465)

the problem the error stack trace does not come fast. sometimes it does .. sometimes it doesnot.

#doesnot work
EMAIL_USER=...
EMAIL_PASSWORD=...
SES_HOST=email-smtp.us-west-2.amazonaws.com
SES_PORT=587
SES_USE_TLS=True

#doesnot work
EMAIL_USER=...
EMAIL_PASSWORD=...
SES_HOST=email-smtp.us-west-2.amazonaws.com
SES_PORT=465
SES_USE_TLS=True


#works on gmail
EMAIL_USER=user_without_gmaildotcom
EMAIL_PASSWORD=...
SES_HOST=smtp.gmail.com
SES_PORT=587
SES_USE_TLS=True

**Comment by dbuxton** [comment]
So the solution is to keep the `EMAIL_BACKEND=django_smtp_ssl.SSLEmailBackend` and make sure it's installed into the environment (assuming you're using docker, add something like `RUN pip install django-smtp-ssl`)

I will open a new issue against cabot-alert-email for not including its potential dependencies.

**Comment by frankh** [comment]
I believe the issue with with using port 465 for TLS.

We have it working with the following settings:

```
EMAIL_HOST=email-smtp.us-east-1.amazonaws.com
EMAIL_USER=*****
EMAIL_PASSWORD=*****
EMAIL_PORT=465
```

(SES_HOST/PORT are aliases of EMAIL_HOST/PORT now)

Try removing the `SES_USE_TLS=True` and see if that works
