### ISSUE TITLE
Deploying cabot on OpenShift 3

### ISSUE THREAD

**Issue by cyril-dussert** [arachnys/cabot#400]
Hi,

I'm trying to deploy Cabot on OpenShift Container Platform, unfortunately, I have errors at some points... I hope you can help me.

I'm trying two different ways : 
- Using Dockerfile : 

I'm creating a new application using `oc new-app https://github.com/arachnys/cabot.git --strategy=docker`
but when the build is starting, I have the following error : http://pastebin.com/y5Gtt6t0

- Using Redhat's Python 2.7 image : 
During the build, all dependecies present on requirements.txt are installed. But, just after, I have this message : http://pastebin.com/uA1P89VM

Obviously, libffi can't be found, do you know how to make it available ?

Do you have any idea which can make me move forward ?

Thanks and Regards

Cyril

**Comment by frankh** [comment]
I'm closing this as we now have a new up-to-date docker image at https://hub.docker.com/r/cabotapp/cabot/

Please re-open if you still can't get it working
