### ISSUE TITLE
Facebook Messenger plugin ImportError

### ISSUE THREAD

**Issue by tjphopkins** [arachnys/cabot#405]
I am writing a Facebook Messenger plugin. I have cabot running locally using the docker containers inside a vagrant environment. 

Having only just written the AlertUserData class and the setup.py (my code can be found at https://github.com/tjphopkins/cabot-alert-fbmessenger/tree/master), I am trying to install the plugin locally. I added my plugin to requirements-plugins.txt:

```
cabot_alert_email==1.3.1
cabot_alert_hipchat==1.7.0
cabot_alert_twilio==1.1.4
git+https://github.com/tjphopkins/cabot-alert-fbmessenger.git#egg=cabot-alert-fbmessenger
```

I removed all existing docker containers and re-ran `docker-compose build`. This completed successfully, having installed the plugins:

```
Installing collected packages: cabot-alert-email, cabot-alert-hipchat, cabot-alert-twilio, cabot-alert-fbmessenger
  Running setup.py install for cabot-alert-email: started
    Running setup.py install for cabot-alert-email: finished with status 'done'
  Running setup.py install for cabot-alert-hipchat: started
    Running setup.py install for cabot-alert-hipchat: finished with status 'done'
  Running setup.py install for cabot-alert-twilio: started
    Running setup.py install for cabot-alert-twilio: finished with status 'done'
  Running setup.py develop for cabot-alert-fbmessenger
Successfully installed cabot-alert-email-1.3.1 cabot-alert-fbmessenger cabot-alert-hipchat-1.7.0 cabot-alert-twilio-1.1.4
```

To confirm, on running `sudo docker-compose run --rm web pip list`, cabot-alert-fbmessenger was present in the list.

I then appended `,cabot-alert-fbmessenger==0.0.1` to the CABOT_PLUGINS_ENABLED variable in conf/development.env.

On running sudo `docker-compose run --rm web bash bin/build-app` I get a Django ImportError:

```
  File "/usr/local/lib/python2.7/site-packages/south/management/commands/__init__.py", line 10, in <module>
    import django.template.loaders.app_directories
  File "/usr/local/lib/python2.7/site-packages/django/template/loaders/app_directories.py", line 25, in <module>
    raise ImproperlyConfigured('ImportError %s: %s' % (app, e.args[0]))
django.core.exceptions.ImproperlyConfigured: ImportError cabot-alert-fbmessenger: No module named cabot-alert-fbmessenger
```

Please could you suggest where I might be going wrong. Thanks!

**Comment by tjphopkins** [comment]
Sorry, I had misnamed the module in the environment variable

**Comment by dbuxton** [comment]
Glad that it worked in the end!
