### ISSUE TITLE
Installing new plugin with fab deploy

### ISSUE THREAD

**Issue by tjphopkins** [arachnys/cabot#407]
I'm creating a new plugin for Facebook messenger.

I have added the repository to requirements-plugins.txt:
`git+https://github.com/tjphopkins/cabot-alert-fbmessenger.git#egg=cabot-alert-fbmessenger`

And I have added the package to CABOT_PLUGINS_ENABLED (in conf/production.env):
`CABOT_PLUGINS_ENABLED=cabot_alert_hipchat==1.7.0,cabot_alert_twilio==1.1.4,cabot_alert_email==1.3.1,cabot_alert_facebook`

It installs without a problem in my development environment using the docker containers.

However when I do a fab deploy to my Digital Ocean instance, I get the following error:
```
[root@188.166.150.141] out: Downloading/unpacking cabot-alert-facebook (from cabot==0.0.1-dev)
[root@188.166.150.141] out:   Could not find any downloads that satisfy the requirement cabot-alert-facebook (from cabot==0.0.1-dev)
[root@188.166.150.141] out: No distributions at all found for cabot-alert-facebook (from cabot==0.0.1-dev)
```

**Comment by tjphopkins** [comment]
I have found that setup.py takes requirements from requirements.txt as you would expect, but separately takes plugin dependencies from the CABOT_PLUGINS_ENABLED environment variable. It does this so that it only installs active plugins, however in doing so it is not aware of the external url from which to download cabot-facebook-fbmessenger and instead is looking in pypi.

**Comment by JeanFred** [comment]
Hi @tjphopkins sorry for the delay in answering.

The fabfile is more or less deprecated these days. Would you have better luck using pip install or Docker?

An alert plugin for Messenger would be a nice addition to the ecosystem :)

**Comment by JeanFred** [comment]
I’ll be closing this as Fabfile is deprecated, but feel free to open an new issue if there are other plugin installation issues :)
