### ISSUE TITLE
All requests return "DoesNotExist"

### ISSUE THREAD

**Issue by xtaetg** [arachnys/cabot#408]
DoesNotExist at /accounts/login/
Site matching query does not exist.
Request Method:	GET
Request URL:	http://localhost:8000/accounts/login/
Django Version:	1.6.11
Exception Type:	DoesNotExist
Exception Value:	
Site matching query does not exist.
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/db/models/query.py in get, line 310
Python Executable:	/usr/bin/python
Python Version:	2.7.12
Python Path:	
['/home/zhangrui/dev/synthesize-master/templates/cabot',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/local/lib/python2.7/dist-packages/cabot-0.0.1.dev0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/cabot_alert_email-1.3.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/cabot_alert_twilio-1.1.4-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/cabot_alert_hipchat-1.7.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_auth_ldap-1.2.6-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/python_dateutil-2.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/twilio-3.4.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pyasn1-0.1.9-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/ndg_httpsclient-0.4.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pyOpenSSL-16.1.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/pytz-2014.10-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/psycopg2-2.5.1-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/psycogreen-1.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/icalendar-3.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/httplib2-0.7.7-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/gevent-1.0.1-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/gunicorn-18.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/djangorestframework-2.4.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_smtp_ssl-1.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_redis-1.4.5-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_polymorphic-0.5.6-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_mptt-0.6.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_jsonify-0.2.1-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_filter-0.7-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_compressor-1.4-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_celery-3.1.17-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/django_appconf-0.6-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/dj_database_url-0.2.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/celery-3.1.23-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/anyjson-0.3.3-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/amqp-1.4.9-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/South-1.0-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/PyJWT-0.1.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/Markdown-2.5-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/python_ldap-2.4.28-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/cryptography-1.7.1-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/greenlet-0.4.11-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/hiredis-0.2.0-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/redis-2.10.5-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/distribute-0.7.3-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/kombu-3.0.37-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/billiard-3.3.0.23-py2.7-linux-x86_64.egg',
 '/usr/local/lib/python2.7/dist-packages/ipaddress-1.0.17-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/enum34-1.1.6-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages/idna-2.2-py2.7.egg',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/home/zhangrui/dev/synthesize-master/templates/cabot',
 '/home/zhangrui/dev/synthesize-master/templates/cabot']

**Comment by dbuxton** [comment]
Closing this as I don't see what's going on - can reopen if more information
