### ISSUE TITLE
Emails not sent when alert triggers

### ISSUE THREAD

**Issue by AlessioMartorelli** [arachnys/cabot#409]
Hi, I've been looking for a product like this for months. Only problem is that it's very hard to get it to work! I've managed to install everything using the cabot-docker repository (using docker-compose).

The emails don't get sent when the alerts trigger
I've also used tcpdump to check if there was any traffic at all and seems like there's traffic only when the metric recovers, even if no email gets actually sent.
This is my configuration:
```
SES_HOST=smtp.gmail.com
SES_USER=myusername@mydomain.com
SED_PASSWORD=mypassword
SES_PORT=587
CABOT_FROM_EMAIL=alerts@mydomain.com
```

Note that these settings work perfectly with another product (graphite-beacon).

Hope I can get help, this could be such a great product!
Thanks
Alessio

**Comment by AlessioMartorelli** [comment]
Updated the description as one of the problems (the rota not showing) finally showed after a very long time. Any chance the download could be triggered manually?

**Comment by dbuxton** [comment]
Re calendar, it updates every 30 mins.

As for email, I suspect that the problem is that by default the email backend might not be compatible with gmail. See https://github.com/arachnys/cabot/issues/217 which looks similar. Also bear in mind that unless the `CABOT_FROM_EMAIL` is a registered sending address with gmail, it might not send properly. I'd recommend using Amazon SES or a similar transactional email service (Sendgrid, Mandrill, etc).

**Comment by AlessioMartorelli** [comment]
Thank you dbuxton,
I'll give it a try with different email providers. I think I have the same issue with Twilio by the way. I don't seem to be able to receive calls either.
I've made sure my user has the mobile phone number set in the database (in the form of +44123123123) and set the variables for the Twilio account:

```
TWILIO_ACCOUNT_SID=ASDQD02UDEOD2EF
TWILIO_AUTH_TOKEN=fmr4i9f9ng39ng39gn
TWILIO_OUTGOING_NUMBER=+44123123123
```

Any idea if there's a place I can have a look to troubleshoot this problem? I've checked in /var/log/cabot but there's no useful information at all in there; it just prints out when it fetches from graphite.

I'd like to get at least one alerting method working, so that I can start using it :)

PS: Every time I edit my environment configuration I'd issue the following command:
`docker-compose up -d`

Thanks again!

**Comment by dbuxton** [comment]
@AlessioMartorelli I'm not sure what you mean by receive calls...

You should be able to look on Twilio's own dashboard to see what's going wrong there. If it's not showing anything, that suggests something's wrong on the Cabot end, but otherwise please post the errors here...

**Comment by AlessioMartorelli** [comment]
@dbuxton sorry maybe I've not explain myself properly.
I've configured a service to alert via Twilio calls and Twilio sms. I'm setting up a threshold so that it triggers so that I could test the configuration. When the alert triggers I was expecting to receive a call and an SMS, but I'm not getting any of them.

I've looked at the Twilio dashboard and I can't see any call coming through so I guess it's a problem with Cabot.
The Twilio section of the configuration has been pasted in my previous comment (replacing the real values). If you can't spot any problem in that configuration the problem might be related to something different in Cabot.
Would you be able to point me to the logs so that I can give you more informations about what is happening?

Again, I've looked into the /var/log/cabot file and I can only see these lines:
```
INFO 2017-01-22 21:42:30,338 connectionpool 78 140689259108160 Starting new HTTP connection (1): graphite.domain.com
```

**Comment by dbuxton** [comment]
Sorry this sounds like a problem that has so many moving parts it's hard to diagnose. 

One thing that might not be clear from the docs is that only Checks that are set to CRITICAL can trigger a phone call for a Service.

To be honest, I'd suggest starting off by getting it working with email, and then move on to debugging Twilio.

**Comment by AlessioMartorelli** [comment]
Yes the checks are set as Critical. I'll try to get the Email working first!

**Comment by AlessioMartorelli** [comment]
Managed to fix the email problem using a different port which seems to be working on gmail (port 465). Now my configuration looks like this:
```
SES_HOST=smtp.gmail.com
SES_USER=myusername@mydomain.com
SED_PASSWORD=mypassword
SES_PORT=465
CABOT_FROM_EMAIL=alerts@mydomain.com
```

**Comment by AlessioMartorelli** [comment]
Can confirm now even Twilio calls work perfectly. I think there was a problem with my environment for some reason. I did create the docker container once again and everything worked.

Many thanks for your support and again, great product!

**Comment by dbuxton** [comment]
Glad to hear it @AlessioMartorelli
