### ISSUE TITLE
checks do not run at specified intervals

### ISSUE THREAD

**Issue by stephenmoloney** [arachnys/cabot#418]
Issue:
- Checks stop sending.
- Only happens when added to either an instance or a service.

Is this expected?

**Comment by dbuxton** [comment]
Can you clarify your issue. You don't get alerts? Or the checks don't actually run?

Checks will run (but not trigger alerts) if they are not attached to a Service or Instance.

**Comment by stephenmoloney** [comment]
Thanks for getting back to me, My issue has changed but only slightly. Since I wrote the above issue, I spent some time upgrading to the latest commit and now my issue has extended to that no checks run unless I click on the `glyphicon-refresh` manually. When I run the check manually, all is well and I get the passed result back. The only issue now is that the checks do not run by themselves - at the specified interval - this is the case whether it is linked to a service or not.

I tried adding some interval in the django admin page and nothing happens still. I did have this up and running before.

One thing, I do not have the `beat` docker container running as I ran into some issues with it but what does the `beat` container do, seems like it should not affect this issue.

Any idea?

**Comment by stephenmoloney** [comment]
Ok, I solved this issue, since I removed the `beat` container, the alerts stopped being triggered.
Fixed by adding them back in to the `worker` docker container.

`command: python manage.py celery worker -A cabot --loglevel=DEBUG --concurrency=16 -Ofair`
changed to
`command: python manage.py celery worker -B -A cabot --loglevel=DEBUG --concurrency=16 -Ofair`
fixed it.
