### ISSUE TITLE
Tag Docker images

### ISSUE THREAD

**Issue by jezdez** [arachnys/cabot#425]
I see you're tagging releases with git, could you also create Docker tags when you push the image to Docker Hub?

**Comment by dbuxton** [comment]
This should now be happening for new tags - @frankh if you bump the minor version tag we should trigger a new build.

I do notice that the Docker Hub build appears to be having issues at the moment: https://hub.docker.com/r/cabotapp/cabot/builds/

Please let's close this when we confirm that tagged builds are going up successfully.

**Comment by frankh** [comment]
@dbuxton it seems it's trying to run "sut" from docker-compose-test.yml and failing (see: https://docs.docker.com/docker-cloud/builds/automated-testing/). I'll try and fix that

Also, I noticed the docker hub login details aren't in 1password - could you send them to me? (although you really shouldn't be working!)

**Comment by frankh** [comment]
We've switched to using github.com/cabotapp/docker-cabot to build docker images. It's not automatic yet but docker images are tagged at https://hub.docker.com/r/cabotapp/cabot/
