### ISSUE TITLE
[help] Where does Cabot store the log?

### ISSUE THREAD

**Issue by vassyz** [arachnys/cabot#432]
Hi

I am not familiar with Django. I installed Cabot using [cabot-docker](https://github.com/shoonoise/cabot-docker/), but emails and Twilio texts aren't being sent. Not being able to find the logs makes thin impossible to debug. In `settings.py` I found the following setup:

```
'log_file': {
    'level': 'DEBUG',
    'class': 'logging.handlers.RotatingFileHandler',
    'formatter': 'verbose',
    'filename': os.environ['LOG_FILE'],
    'maxBytes': 1024 * 1024 * 25,  # 25 MB
    'backupCount': 5,
},
```

The `LOG_FILE` points to a file that doesn's exist `/var/log/cabot`. Would anyone be able to point me in the right direction?

**Comment by frankh** [comment]
Hi vassyz,

cabot-docker isn't officially supported (We will be releasing our own docker solution very soon)

However, I would guess the log files are going to /var/log/cabot `within` the docker container. You would either need to enter the container to inspect the logs, or mount /var/log to a folder on your machine

**Comment by vassyz** [comment]
Hi @frankh. Thank you for your reply. I already checked the container. My post is related to the container itself. There is no `/var/log/cabot` on that container. I created one, with write permissions, but nothing gets put into it.

How soon will you be releasing your Docker integration? I'm actively looking for an open source monitoring solution to use on our systems.

**Comment by frankh** [comment]
@vassyz there's still lots of automation and documentation to do, but the first working cabot image is uploaded at https://hub.docker.com/r/cabotapp/cabot/

Let me know if you have any issues using it
