### ISSUE TITLE
Ubuntu 14.04 wrong static file path (getting 404's)

### ISSUE THREAD

**Issue by Exocomp** [arachnys/cabot#438]
Cabot starts with (foreman start -e conf/production.env) but the static files (css/js/png) are not getting served with the correct path, the browser shows 404's, see the paths below:

http://alert/static/CACHE/css/2ede5f79904a.css
http://alert/static/CACHE/js/27b97496ae85.js
http://alert/static/arachnys/img/icon_48x48.b733b0a14763.png

Is there quick fix for this ? :)

**Comment by JeanFred** [comment]
@Exocomp Could you solve the issue ? :)

**Comment by Exocomp** [comment]
I got it sorted out, it was a path problem with nginx and also the static folder at least with my setup.
