### ISSUE TITLE
Update Email Encryption Protocol (SMTPS vs STARTTLS)

### ISSUE THREAD

**Issue by Exocomp** [arachnys/cabot#439]
I was using Gmail with port 587 where Cabot was failing exception below, but with port 465 it is working.

From Googling a bit it turns out that Gmail port 465 is using the old SMTPS protocol which Cabot supports (since it is working) and Port 587 uses the STARTLS portocol (where Cabot is failing).  

So apparently SMTPS has been deprecated for about 15 years now so it's probably a good idea to get Cabot updated too.  This is from me Googling around for a few minutes so when you decide to update you'll probably want to do through research before implementing a solution.

With port 587:

11:46:09 celery.1 | [2017-02-25 17:46:09,202: ERROR/Worker-1] Could not send Email alert: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)
11:46:09 celery.1 | Traceback (most recent call last):
11:46:09 celery.1 |   File "/home/ubuntu/2017-02-25-206abcd/cabot/cabotapp/alert.py", line 40, in send_alert
11:46:09 celery.1 |     alert.send_alert(service, users, duty_officers)
11:46:09 celery.1 |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/cabot_alert_email/models.py", line 49, in send_alert
11:46:09 celery.1 |     recipient_list=emails,
11:46:09 celery.1 |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/mail/__init__.py", line 62, in send_mail
11:46:09 celery.1 |     return mail.send()
11:46:09 celery.1 |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 303, in send
11:46:09 celery.1 |     return self.get_connection(fail_silently).send_messages([self])
11:46:09 celery.1 |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
11:46:09 celery.1 |     new_conn_created = self.open()
11:46:09 celery.1 |   File "/home/ubuntu/venv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 58, in open
11:46:09 celery.1 |     self.connection = connection_class(self.host, self.port, **connection_params)
11:46:09 celery.1 |   File "/usr/lib/python2.7/smtplib.py", line 801, in __init__
11:46:09 celery.1 |     SMTP.__init__(self, host, port, local_hostname, timeout)
11:46:09 celery.1 |   File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
11:46:09 celery.1 |     (code, msg) = self.connect(host, port)
11:46:09 celery.1 |   File "/usr/lib/python2.7/smtplib.py", line 316, in connect
11:46:09 celery.1 |     self.sock = self._get_socket(host, port, self.timeout)
11:46:09 celery.1 |   File "/usr/lib/python2.7/smtplib.py", line 807, in _get_socket
11:46:09 celery.1 |     new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
11:46:09 celery.1 |   File "/usr/lib/python2.7/ssl.py", line 933, in wrap_socket
11:46:09 celery.1 |     ciphers=ciphers)
11:46:09 celery.1 |   File "/usr/lib/python2.7/ssl.py", line 601, in __init__
11:46:09 celery.1 |     self.do_handshake()
11:46:09 celery.1 |   File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
11:46:09 celery.1 |     self._sslobj.do_handshake()
11:46:09 celery.1 | SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

**Comment by frankh** [comment]
Hi @Exocomp,

I believe this should be fixed since https://github.com/arachnys/cabot/pull/427 was merged in. (v0.8.2+)

I currently have a deployment working with the following email settings

```
EMAIL_HOST=smtp.gmail.com
EMAIL_USER=********@gmail.com
EMAIL_PASSWORD=*********
EMAIL_PORT=587
EMAIL_USE_SSL=
EMAIL_USE_TLS=1
```

**Comment by Exocomp** [comment]
Thanks I just tried those settings and it worked.  Note:  You may want to update the production.env and just put in a note on how to use it.  :)
