### ISSUE TITLE
Question on expected behavior

### ISSUE THREAD

**Issue by Exocomp** [arachnys/cabot#441]
I'm a little confused on the concept of Services in relation to Checks with alerts/notifications.  

Let me give a scenario.

**Service**:  Web Farm
**Checks**: 
CPU Warning (when CPU > 50%)
CPU Error (when CPU > 75%)
CPU Critical (when CPU > 95%)

Memory Warning (when memory > 75%)
Memory Error (when memory > 85%)
Memory Critical (when memory > 95%)

Given this setup when the CPU goes up quickly to 100%, the warning is triggered with an alert.  
However, when the Error is triggered is doesn't generate an alert (no email or HipChat).  Same goes for Critical, no email alert or HipChat.

Then after 10 minutes, it finally does send an alert with email and HipChat indicating the correct status of all checks.  This seems a bit odd to me, is this correct functionality?  Shouldn't an Error alert and Critical alert be sent right away instead of waiting 10 minutes?

Also, if during this time a memory alert is triggered there is no email alert or HipChat alert until 10 minutes passes.  Why wait the 10 minutes ?

**Comment by frankh** [comment]
That definitely doesn't sound right

What are you check intervals? Is it possible they're only running every 10 minutes?

**Comment by Exocomp** [comment]
The minutes between each check is set to 1 minute.  I suppose that is just how it works.  There is a work around in that you can create a separate service for each check that way each alert independently.

**Comment by dbuxton** [comment]
I think this is worth reopening. This is just lazy logic (mea maxima culpa) - if you look at https://github.com/arachnys/cabot/blob/206abcd6e7aa77e274733467441d29bd2a3eeed5/cabot/cabotapp/models.py#L174, we have access to `last_alert_status` and so it would be easy to implement the behavior you want, @Exocomp 

We only have three thresholds so it's pretty straightforward to enumerate the possible transitions and what we would want behavior to be in any given case...

**Comment by Exocomp** [comment]
Alrighty reopened, to me it does make sense to have checks in a service trigger email/hipchat/phone independently (or if higher priority is triggered ignore the lower ones) or at least give an option for the user to select.

**Comment by frankh** [comment]
@Exocomp @dbuxton I've created a pull request to fix this, let me know what you think

**Comment by Exocomp** [comment]
[Make alerts trigger if they are more severe than previous alert](https://github.com/arachnys/cabot/pull/442)

Yes I like it.

**Comment by Exocomp** [comment]
Will it be based per metric?  Meaning if another metric of the same severity gets triggered, will it send an alert?  Only make sense to me that it should.

**Comment by frankh** [comment]
@Exocomp no and I don't think it should.

In that case in a total system failure you would be bombarded by every single check

**Comment by Exocomp** [comment]
What if it is not a total system failure, say you have 2 important metrics your checking in a service.  Important metric 1 fails and it is alerted right away.  Then important metric 2 fails but it is not alerted right away until 10 minutes.  What say you in that case ?

**Comment by frankh** [comment]
The idea is that you are only alerted on the state of a service, not individual checks.

If the service is already in for example 'error' state, then you should already be working to fix it so shouldn't need another alert to say it's broken for a different reason.

Maybe a good idea would be to have a feature where you could escalate to a higher severity if you have multiple checks failing, e.g. 3 failing error checks would trigger a critical alert

**Comment by Exocomp** [comment]
yea I see your point and it make sense if one person was maintaining the service and they had access to Cabot to check right away to see what other checks are failing.

But what if you don't have access to Cabot right away and you are relying on alerts to tell you what's wrong.  Currently when you get an email it tells you what failed and what is passing.  So you get an email that important metric 1 failed but in that email it says that important metric 2 is passing (but really it is not) and then 10 minutes later you get a summary indicating important metric 2 is failing also.  

Also if more than one person is maintaining the service and one guy is to maintain important metric 1 and another guy is to maintain important metric 2 then the second guy will just sit and not do anything until 10 minutes later when a summary is sent.

But then again 10 minutes of a wait isn't too bad I guess, although I do think it is good to know right away.

**Comment by Exocomp** [comment]
Maybe an option for each check that if it fails you definitely want to be notified right away so even if another check of the same severity failed it still sends an alert.  Then folks can decide. :)

**Comment by dbuxton** [comment]
Just to give my 2¢ on this @Exocomp - our experience has been that getting dozens of notifications really interferes with our ability to fight fires. 

The way we have things set up, I wouldn't want to have multiple levels of `ERROR` notifications sending new alerts, but I do see a case for having additional `CRITICAL` alarms trigger additional alerts. 

We haven't really thought hard about multiple people working simultaneously etc, Cabot is really designed to get you out of bed/away from your TV and onto your laptop to debug rather than giving you a real-time view of everything that's going wrong as it's detected. (At least, through the hipchat/slack/email/etc alerts.) 

I think that if that's what you want, I'd suggest that we put more effort into having the dashboard auto-update so that service statuses are made more apparent, and failing checks are notified as alarms on the web interface. That way Slack or whatever brings you to the dashboard and then the dashboard is the single source of truth as to what's going on. Maybe we can do that in 1.0 @frankh ;)

**Comment by Exocomp** [comment]
I'm happy camper getting "[Make alerts trigger if they are more severe than previous alert](https://github.com/arachnys/cabot/pull/442)" out of this. :)

I'm all for simplicity and agree that too much noise is not really beneficial sometimes.  Although an option for each check to send an email right way (disabled by default) if it is triggered make sense to me at least right now but if abused I can see how it can be a problem (even though it would be up to the person that is setting it up).  

But for sake of simplicity may be just leave it as is.

**Comment by frankh** [comment]
This is now released in 0.8.5 so i'm going to close the issue.

**Comment by Exocomp** [comment]
@frankh @dbuxton I just wanted to say that this change "[Make alerts trigger if they are more severe than previous alert](https://github.com/arachnys/cabot/pull/442)" is working well for me.  :)

Thank You!
