### ISSUE TITLE
Feature request: Add maintenance mode

### ISSUE THREAD

**Issue by Exocomp** [arachnys/cabot#447]
I currently don't see an option for this, if one exists already then my apologies this can be closed.

**Feature**:  To have Cabot enter maintenance mode at a scheduled period of time.  During this time Cabot will not trigger any notifications/alerts.  Then after the maintenance mode is over, Cabot should automatically resume checks.  The reason for this is during maintenance/deployments lots of things are going on, services are taken down and brought back up and usually during this time there is no need to alert as folks are already aware and working.  

Also, there should be an option to notify stakeholders as it enters maintenance mode and as it exists maintenance mode.

**Comment by dbuxton** [comment]
I don't think we're going to do this @Exocomp - Services can already have alerts disabled and there's also a button that allows users to signal they are working on a broken service. To apply this globally seems unnecessary to me as all but the smallest deployments are likely to have a number of independent services, not all of which will be affected by a global maintenance.

That said if you were willing to do a PR we would look at it as I don't see any harm in having the feature, just not something we would spend time implementing.

**Comment by Exocomp** [comment]
No worries, it's just a good thing to have so you don't have to manually disable services and manually enable them again (maybe forgetting to enable again).  It's just that I know when I have planned deployments I will be disabling some services so no point in it alerting me.  Perhaps at the time of creating the planned maintenance you could even select the services that would be affected.

Not a big deal though just if you guys decide to add it in the future at least I would find it beneficial. :)

**Comment by frankh** [comment]
Hi @Exocomp , while we still don't technically have maintenance mode, the latest version has a settings page for alert plugins that allows you to disable plugins.

This means to disable all alerts you just need to disable all the plugins you use

**Comment by rmrf** [comment]
Hi @frankh, I have a test on our cabot insance, after disabled those plugins through django-admin backend (`/admin/cabotapp/alertplugin/`), alert can still be send out. so which commit cover the alert plugins disable fucntion?

**Comment by frankh** [comment]
@rmrf it should work in version 0.10.4 - since 0.9.2 you can see your version at `/about`

There should be a `Plugin Settings` option in the user dropdown in the top-right
