### ISSUE TITLE
Feature Request: Ability to check/alert based on comparison of two metrics

### ISSUE THREAD

**Issue by Exocomp** [arachnys/cabot#459]
Hi,

I don't see an option for this currently, if one exists I would love to know how to do it.  Here is one example of my use case:

Check:  SQL Page Lookups Per Sec Warning
Metric: SQL Page Lookups per sec

The warning case is that if page lookups per second exceeds batch requests per second * 100.

So basically in order for me to generate a warning I need data for two metrics available in a single check in Cabot.  Hope that make sense.

Thanks,
E

**Comment by Exocomp** [comment]
So for example in Cabot for a check if I had something like:

Metric 1:  <my first Graphite metric goes here>
Metric 2:  <my second Graphite metric goes here>

Check Type:  Metric 1 > Metric 2

**Comment by JeanFred** [comment]
You can compose metrics with Graphite, and thus I believe you can achieve this with diffSeries(Metric2, Metric1) and ask Cabot whether it’s greater than zero.

Let me know if that works!

**Comment by Exocomp** [comment]
@JeanFred your right, it looks ugly and not very readable (relative) but it works!  Now if only I get "When Guards" for checks, I'll create a separate FR for that.
