### ISSUE TITLE
Adopt cabot-alert-slack plugin

### ISSUE THREAD

**Issue by JeanFred** [arachnys/cabot#465]
We have been consolidating the various plugins under the @cabotapp organisation. We have had interest for the Slack plugin.

Steps:

- fork the lblasc/cabot-alert-slack plugin
- get it to work with our newer Django versions
- if possible, move the Github repo under the cabotapp umbrella and update on Pypi.

@frankh is taking the lead on this. @lblasc − does that sound good to you? :)

**Comment by lblasc** [comment]
Fine with me, I'm willing to transfer ownership of the repo to the @cabotapp org

**Comment by JeanFred** [comment]
@lblasc Fantastic! The repo now lives at https://github.com/cabotapp/cabot-alert-slack − you should have write access too :)

**Comment by frankh** [comment]
@lblasc thanks! Could you also transfer the pypi package to "arachnys"? https://pypi.python.org/pypi/cabot-alert-slack/0.6

**Comment by lblasc** [comment]
@frankh done

**Comment by frankh** [comment]
Thanks

This is now merged into master

**Comment by dankonino** [comment]
Hey guys. I wonder if it's still up to date. I did everything up till ```Add cabot_alert_slack to the installed apps in settings.py```
I was not able to receive the alerts, I do with different stuff. I wonder if you can give me a hint ;)
