### ISSUE TITLE
Shell alerts

### ISSUE THREAD

**Issue by strongh** [arachnys/cabot#47]
More and more folks will want a wider variety of alerts. The existing built-in alert channels are likely the most commonly desired, but there are probably many other less-used channels that users would like to use (in our case, it's slack, and I see other specific suggestions in the issues).

For our use case, and many similar cases, we could go through a generic shell alert. We would configure a shell snippet, and perhaps relevant cabot variables (e.g. names of check and service that are failing) could be passed in as environment variables. For our case, and likely most others, a `curl` 1-liner is all we need.

This would give users a ton of flexibility. Cabot would immediately be able to configurably  alert on vastly more possibly channels.

(Another similar path could be a generic HTTP hook channel, where users can construct HTTP requests as well as endpoints. However that would be probably be more work and would serve fewer use cases.)

**Comment by frankh** [comment]
I'm cleaning up some old issues

I don't think we're going to implement this due to security concerns
