### ISSUE TITLE
API documentation ?

### ISSUE THREAD

**Issue by VAdamec** [arachnys/cabot#477]
I didn't find any API documentation (create/modify checks/alerts/subscriptions). Is there any ?

**Comment by dbuxton** [comment]
There is some in the readme: https://github.com/arachnys/cabot#api

We should add a page to the microsite though.

**Comment by VAdamec** [comment]
Well it's very brief :-) I'm trying to do Ansible role which will create service + needed instances and checks and I'm quite lost. Is this sequence ok/logic ?

1. add service and instance checks (icmp/graphite/http/...) - save ```ID```
2. add instances - assign instance checks, somehow
3. add service + add all IDs of all created checks - API ```status_checks``` field array

Via UI I see 'Status checks' and 'Service set' option in instance configuration but I'm missing same in API (/api/instances/?format=api) I would expect same as service has (array status_checks) at least. Did I miss something, how API can be used to create full service with all checks and instance ? Maybe some simple example in documentation will help.

**Comment by VAdamec** [comment]
Ok, well it's very brief but better than nothing :-) I'm trying to create Ansible role for creating whole service/instance/checks during new VM instances provisioning so any hint will be helpful, but I can survive with Django REST framework.

**Comment by JeanFred** [comment]
@VAdamec I had started an Ansible module for that. I can look into sharing it somewhere if that would be helpful

**Comment by hugodias** [comment]
@JeanFred your CLI helped me a lot to understand how the API Works. Thanks!
