### ISSUE TITLE
Deprecate/remove the Fabfile / bash install scripts 

### ISSUE THREAD

**Issue by JeanFred** [arachnys/cabot#493]
We have made great strides in Cabot distribution:

* Cabot is now packaged in Pypi ;
* we have an [Ansible role](https://github.com/cabotapp/ansible-cabot)
* we have a [Docker-compose setup](https://github.com/cabotapp/docker-cabot)

I don’t see any reason to use the Bash scripts now, and would suggest removing them.

Thoughts?

**Comment by thomasleveil** [comment]
when trying to contribute on this project, I was quite confuse with (should I / how to) use the fabfile. If they don't help anymore, better removing them.

**Comment by frankh** [comment]
They should definitely be removed

**Comment by skylerbunny** [comment]
What is the supported method of performing the equivalent of a 'fab backup'? I have been crafting an ansible playbook to deploy cabot via docker-compose, which is great, except that I have no way of (in a documented fashion that I can find) pulling data I create out of the containers - and the docs still reference doing backups by this old method, in the implicit sense of suggesting using fab here: http://cabotapp.com/use/configuration.html

**Comment by skylerbunny** [comment]
See also http://cabotapp.com/use/operations.html , which explicitly mentions using 'fab backup'.

**Comment by thomasleveil** [comment]
Try `docker-compose exec db pg_dump cabot > cabot.sql`

**Comment by skylerbunny** [comment]
Using the framework in https://github.com/cabotapp/docker-cabot , the correct command is this (and thanks for the hints to get me started):

`docker-compose exec postgres pg_dump -U postgres postgres > cabot.sql`

**Comment by JeanFred** [comment]
@skylerbunny Thanks! I added this command verbatim to the Operations chapter :)
