### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by jnhmn** [arachnys/cabot#496]
If I run the test suite on Arch Linux,
Following tests fail every time:
test_alert_alternating_severity
test_alert_decreasing_severity
test_alert_increasing_severity
(fake_sent_alert.call_count != 1)
test_clenup_batch
(StatusCheckResult.objects.all().count() = initial_results+1)

If needed, I can attach the whole trace.

**Comment by frankh** [comment]
how are you running the tests?

The full trace would definitely be helpful

**Comment by frankh** [comment]
I'm not able to reproduce. From a fresh Arch Linux install I ran:

```
$ pacman -Syu git python2 python2-pip gcc lessc coffee-script
$ git clone https://github.com/arachnys/cabot
$ cd cabot/
$ pip2 install -r requirements.txt -r requirements-dev.txt -r requirements-plugins.txt
$ (set -a && source conf/default.env && source conf/test.env && python2 manage.py test -v2)
```

(I appreciate the sourcing the env files isn't the most obvious thing in the world)

**Comment by jnhmn** [comment]
I followed your official instructions:
`
git clone https://github.com/arachnys/cabot
cd cabot/
cp conf/development.env.example conf/development.env
docker-compose build
docker-compose run --rm web python manage.py test -v2
`

With your above provided commands it works now, without docker.

**Comment by frankh** [comment]
ah I didn't realise you meant the docker tests...

The docs were actually out of date, the best way to run the tests (how the CI does it), is:

```
    $ docker-compose -f docker-compose-test.yml build
    $ docker-compose -f docker-compose-test.yml run --rm test
```

However, running the tests how you did it *should* work

**Comment by frankh** [comment]
Just looked into it. The reason they fail is that CELERY_ALWAYS_EAGER is not set in development.env (which is correct, as it has a worker). The unit tests don't wait for the worker to execute the tasks and so fails.

For the tests to work in development you have to set `CELERY_ALWAYS_EAGER=True` in development.env - however it's better to just use docker-compose-test.yml as shown above
