### ISSUE TITLE
Fabric runs createsuperuser on every deploy

### ISSUE THREAD

**Issue by GregoryAveryWeir** [arachnys/cabot#497]
The current fabfile tries to create a superuser every time it deploys. This is inconvenient if you're just deploying a new release. Can this be made optional?

**Comment by dbuxton** [comment]
#493 should fix this (albeit simply by removing the fabfile entirely ;)

**Comment by JeanFred** [comment]
Hi @GregoryAveryWeir, as David indicated, we are in the process of deprecating the Fabfiles because we think we now have much better deployment mechanisms. Do you think these cover all your use cases? Please weigh-in in #493 :)

**Comment by JeanFred** [comment]
The Fabfile is now removed ;)
