### ISSUE TITLE
Graphite checks fail on any value instead of current

### ISSUE THREAD

**Issue by frankh** [arachnys/cabot#499]
I'm not sure if this is expected, but for example if a disk space check goes off and you delete some files, even though the graph shows the disk space is back up the check will fail until the disk space is fine on the whole graph, not just the current value

cc @JeanFred @dbuxton

**Comment by dbuxton** [comment]
It should basically be watching for anything that's failed since the last check - otherwise you might have intermittent breaches of the threshold that you would miss because the last value passed.

Does that make sense?

**Comment by frankh** [comment]
yeah makes sense, didn't realise the graph period was the same as the check frequency
