### ISSUE TITLE
Sending email without SSL/TLS requires undocumented option

### ISSUE THREAD

**Issue by skylerbunny** [arachnys/cabot#500]
To set up a cabot environment where a destination email server does not support either SSL or TLS, a line is required that is not present in the example files (thus, required me to go to the source to discover it).

This is a correct configuration for a server that supports neither:
```
EMAIL_HOST=myhost.example.com
EMAIL_PORT=25
EMAIL_USE_TLS=0 # but at least this defaults to false, it doesn't have to be in the file
EMAIL_USE_SSL=0 # ...and this absolutely DOES need to be in the file

```
'EMAIL_USE_SSL' is not described anywhere in https://github.com/arachnys/cabot/blob/master/conf/production.env.example . Its default is 'True', so if you are unfortunate enough to have a server that doesn't support it, you have to resort to logs, and then examining the source, to figure out what to do.

**Comment by frankh** [comment]
Hi @skylerbunny ,

Unfortunately our docs are really out of date in a lot of areas, - I'll try and fix this soon

**Comment by hartwork** [comment]
`EMAIL_USE_SSL` made its way in by now. Is this ticket fixed by now?

**Comment by frankh** [comment]
I think so please reopen if it's still an issue
