### ISSUE TITLE
Twilio unable to fetch call informations

### ISSUE THREAD

**Issue by AlessioMartorelli** [arachnys/cabot#508]
Hi! I've been having issues with Twilio calls. When I receive the phone call I get something like "Sorry, application error". I went on the Twilio console and seems like it can't fetch the XML containing the info for the call.

For some reason it gets redirected with a 302 to the login page, which makes sense. Was just wondering how it used to work before and if there's anything I have to tweak in order to let Twilio fetch the XML.

Note that I'm running Cabot version 0.10.5, listening on port 500 with an apache reverse proxy in front of it with the following configuration:
```
<VirtualHost *:80>
    #ProxyPreserveHost On

    # Servers to proxy the connection, or;
    # List of application servers:
    # Usage:
    # ProxyPass / http://[IP Addr.]:[port]/
    # ProxyPassReverse / http://[IP Addr.]:[port]/
    # Example: 
    ProxyPass / http://127.0.0.1:5000/
    ProxyPassReverse / http://127.0.0.1:5000/

    ServerName myhost.com
</VirtualHost>
```

This is the debug page in Twilio:
<img width="2320" alt="screen shot 2017-05-03 at 21 08 59" src="https://cloud.githubusercontent.com/assets/9568357/25679548/a1e860d4-3045-11e7-9010-05c9bfcfc9cb.png">

Thanks

**Comment by MrSaints** [comment]
I can confirm that this is happening on our version as well.

**Comment by frankh** [comment]
I figured out the cause of it, there's a fix on master but the tests are breaking - will try and get a fix out today

**Comment by AlessioMartorelli** [comment]
Thanks @frankh !
Just to let you know I've tried the master branch but I seem to have the same problem. Will wait for your fix, thanks.

**Comment by frankh** [comment]
@AlessioMartorelli I've just pushed 0.10.6 which should have fixed the issue - it's on pip but i haven't uploaded the docker image yet, should be there in a few minutes

btw, the Alert test feature for twilio still has this issue, but for real alerts it works

**Comment by AlessioMartorelli** [comment]
Can confirm that it works now! Thanks a lot @frankh !
