### ISSUE TITLE
Cabot <> Jenkins integration

### ISSUE THREAD

**Issue by leec651** [arachnys/cabot#514]
Hi there,

I'm not sure if this is the proper channel to ask questions. Let me know if it's not.

I am trying to use Cabot to alert my team when a Jenkins job fails. After configured, the link on top right does take me to the correct Jenkins job page. However, all my Cabot checks succeeded with the Error message "Error fetching from Jenkins - No JSON object could be decoded".

What is Cabot actually try to fetch from Jenkins? How do I properly configure this? Can someone please point me to the right direction?

Documentation: http://cabotapp.com/use/jenkins-checks.html

Cabot:
![image](https://cloud.githubusercontent.com/assets/962617/26179797/899e0da0-3b1a-11e7-85fd-a6e6f8b539aa.png)

Jenkins:
![image](https://cloud.githubusercontent.com/assets/962617/26179818/97c573b4-3b1a-11e7-94d7-022aeb014b8f.png)

**Comment by thomasleveil** [comment]
Check that the [`JENKINS_API` url, `JENKINS_USER` and `JENKINS_PASS`](http://cabotapp.com/use/configuration.html#jenkins-integration) are corrects in the Cabot mail configuration file.

**Comment by leec651** [comment]
Hi all,

My colleague was able to figure out what went wrong. We had to redeploy Cabot with the environmental variables set with the correct Jenkins username and password. The confusing part was that even though Caobt failed to authenticate with our Jenkins, it still shows "succeeded".

Regards
