### ISSUE TITLE
Using docker install cannot run fabric

### ISSUE THREAD

**Issue by OverByThere** [arachnys/cabot#515]
Following install here: http://cabotapp.com/qs/quickstart.html

I now have changed SMTP settings and I want to restart the server, docs ask to use fabric ( http://cabotapp.com/use/operations.html ), this fails:
```
root@svrmon:/var/www/html/docker-cabot# fab restart -H ubuntu@127.0.0.1

Fatal error: Couldn't find any fabfiles!

Remember that -f can be used to specify fabfile path, and use -h for help.

Aborting.
```

What is the *current* correct way to restart the server?

**Comment by JeanFred** [comment]
@OverByThere Sorry for the delay in answering.

Tha fabfile has been deprecated − see #493. We are in the process of updating that documentation chapter.

If you are using the docker-compose setup, you may restart with `docker-compose restart web` ; if you are using systemd/init.d scripts, you may use `sudo service cabot restart`

**Comment by JeanFred** [comment]
@OverByThere I removed all references to Fabric from the Operations chapter.

**Comment by JeanFred** [comment]
Closing this since the documentation has been updated on that point.
