### ISSUE TITLE
Production setup, restart, reconfiguration, upgrade, backup/restore

### ISSUE THREAD

**Issue by hontvari** [arachnys/cabot#517]
The operations related chapters of the documentation are out-of-date. 

The Configuration chapter refers to fab, and the 5th step of the quickstart guide. There is no 5th step. Actually there is no quickstart guide at all, it is called Get started. Moreover, the Get started page refers to the cabotapp/docker-cabot repo, which do not contain fab file, so I doubt it would work. In another issue report I have read, that fab is obsolete now anyway. 

The arachnys/cabot repo contains both fab and docker-compose files. This is getting quite confusing. Does the Get started page describe the installation method for a quick test? Or is this the recommended way of production installation too?

The SMTP variables in the Configuration page are obsolete. The MySQL section is obsolete too, and there is an issue report that migrations do not work with MySQL.

The Deployment page talks about upgrading. I I doubt that it is up-to-date. All it says "Upgrading to a new version should be as simple as merging in changes from upstream and deploying over the top of your existing install." Which upstream? cabotapp/docker-cabot or arachnys/cabot? How should I deploy? docker-compose up -d as it is written on the Get started page?

The Operations page would describe how to stop, start and backup cabot. But it refers to fabric, so it will not work. I was able to stop cabot using service docker stop, but could not start is later, because I would have to give a specific container (which of the 5?). service docker restart strangely works, it starts all 5 containers. And of course I am very interested in how should I backup cabot on a production setup. In another issue somebody mentioned a docker PostgreSQL command, I am not sure how up-to-date is that, it would be great if it were documented for us, who only know MySQL.

**Comment by hontvari** [comment]
I figured out how to reconfigure cabot: 
In your docker-cabot git repository directory, which was used during install, edit `conf/production.env` and than 
`run docker-compose up -d`
This stops the containers and rebuild them as necessary, and restarts them. The data in the PostgreSQL database remains intact.

**Comment by JeanFred** [comment]
@hontvari Glad you found a solution!

Yes some of our docs are vastly out of date with the move to docker-compose and the deprecation of Fabric scripts (see #493). We will try to address this soon ; but if you have time submit a PR to the `gh-pages` branch that would be greatly appreciated :)

**Comment by hontvari** [comment]
Another thing I figured out: 
In order to see the cabot/python logs, run
`docker logs dockercabot_web_1`
