### ISSUE TITLE
Can I run this without Docker?

### ISSUE THREAD

**Issue by seanvree** [arachnys/cabot#520]
Great project. 

Possible to run this without docker and just as a python script?

THX!

**Comment by JeanFred** [comment]
Hi @seanvree,

Indeed, using Docker is not mandatory. You can install Cabot as a PIP package. We have an [ansible role](https://github.com/cabotapp/ansible-cabot) to do this kind of installation − even if you cannot/don’t want to use Ansible, it will outline the steps you need for a production deploy of Cabot.

**Comment by seanvree** [comment]
got it @JeanFred  - thanks! 

i'm trying to run this on windows....so can I just clone the repo and run one of the .py files?

**Comment by seanvree** [comment]
@JeanFred  - Hey, am I missing something when you say " it will outline the steps you need for a production deploy of Cabot."  I'm not seeing those instructions anywhere, where should I be looking

https://github.com/cabotapp/ansible-cabot

**Comment by JeanFred** [comment]
@seanvree Right, that was a bit unclean :). The [tasks](https://github.com/cabotapp/ansible-cabot/blob/master/tasks/main.yml) in the Ansible role do install Cabot, so one could roughly follow their intent manually to get there.

However they make sense on Linux, not on Windows (there is no Systemd scripts on Windows for example). We do not support deployment on Windows. If you really cannot use a Unix system, then Docker will probably be your best bet :)

**Comment by seanvree** [comment]
Got it! Thanks!

**Comment by RazrSaw** [comment]
Someone can help me please? I'm trying to run cabot, but I have no idea how to do it without Docker. I have an OpenVZ VPS, but Docker is not supported because of the 2.6 kernel. I installed cabot with `pip install cabot` then I tried to run `# cabot` but could not find it. Thank you in advance!

**Comment by mluczak** [comment]
Apparently the author of cabot decided the only way to run his app will be through docker-compose. Even vagrant doc disappeared from the repo. This is sad. Not everyone wants to be part of the docker hype. I would probably waste less time implementing my own solution than trying to run this outside of docker.

**Comment by frankh** [comment]
There's an ansible playbook cabot here: https://github.com/cabotapp/ansible-cabot

Or you can install the dependencies manually with `apt-get install gcc musl-dev libffi-dev libldap2-dev libsasl2-dev` and then simply `pip install cabot` (with pip<10 atm)
