### ISSUE TITLE
Integrating with Hosted Graphite

### ISSUE THREAD

**Issue by kowsik** [arachnys/cabot#53]
Hi there, I'm doing a trial on hosted graphite and was curious if and how you integrate with their access keys. Your documentation suggested Base64 auth with Graphite user/pass. Is it simply a matter of using their access key as the username with no password?

**Comment by daveconcannon** [comment]
Somehow, we only saw this ticket now...

For anyone still looking - we've updated our documentation to include more detailed instructions on how to get Hosted Graphite working with Cabot here: 

http://docs.hostedgraphite.com/integrationguide/ig_alerting.html#using-hosted-graphite-with-cabot

**Comment by bufke** [comment]
These instructions don't work for me. I get `{"status": "error", "message": "403 Client Error: Forbidden"}` How can I debug this?

**Comment by daveconcannon** [comment]
Hey there - 
   Can you drop me a mail so we can debug further? dave [at] hostedgraphite.com. It's likely your access key is missing a trailing slash or something else, happy to help you figure it out.

Dave
