### ISSUE TITLE
Can'  create the alert when the value differ expected condition

### ISSUE THREAD

**Issue by lamhaison** [arachnys/cabot#532]
I want check my_status code ( collecting from curl plugin in collectd agent). I only get status code of request(200, 500). I want to alert when status different 200. I can't set alert because I can't find this condition different when create a alert. I think we need allow to this condition.

**Comment by JeanFred** [comment]
Hi @lamhaison,

I’m sorry, I’m not sure I understand your original question.

If this was about having the Cabot HTTP check against several expected status codes, then indeed that’s not possible at the moment. Is that what you were trying to achieve ?
