### ISSUE TITLE
mandatory variables to Update to v0.11.0

### ISSUE THREAD

**Issue by pablodgonzalez** [arachnys/cabot#546]
In Migration 05, there are mandatory variables JENKINS_API, JENKINS_USER and JENKINS_PASS.
But when there isn't jenkins checks and environment variables are no necessaries, the migrations fails.

The workaround is define the environment variables with an aleatory value but is necessary add this tip to docs or maybe leave those as optionals

cheers!

**Comment by JeanFred** [comment]
Indeed! Thanks for reporting (note to self: this is [L21]( https://github.com/arachnys/cabot/blob/master/cabot/cabotapp/migrations/0005_auto_20170818_1202.py#L21))
