### ISSUE TITLE
Create a User and should have only read access to the dashboard

### ISSUE THREAD

**Issue by manojDevOps** [arachnys/cabot#549]
Hi Team,

I want to create a user and he cannot add or remove checks,service,instances etc, he should have only read access. Will it be possible in Cabot ?

Thanks,
Manoj

**Comment by dbuxton** [comment]
Not at the moment.

**Comment by manojDevOps** [comment]
Thanks for your response. Can we expect this soon ?

**Comment by JeanFred** [comment]
@manojDevOps A public view system was added by @pablodgonzalez in #533. Services can be individually tagged as public / not public, and unlogged users can see a list of these public services. Would that fit your usecase ?

**Comment by manojDevOps** [comment]
Thanks @JeanFred , yes I am looking exactly for this kind and now I got **Is Public** button to enable which will display my service in the public home with only read access.
