### ISSUE TITLE
SMS Alert to multiple phone numbers

### ISSUE THREAD

**Issue by manojDevOps** [arachnys/cabot#563]
Does Cabot allow to send SMS alert to multiple phone numbers ?

**Comment by dbuxton** [comment]
AFAIK yes - it will text whoever is listed on the service.

It doesn't allow you to call multiple people as things stand.

@frankh @JeanFred correct me if I'm wrong

**Comment by manojDevOps** [comment]
@dbuxton Thanks for ur quick response. How do I list multiple phone numbers on the Cabot dashboard ?
I tried using comma, semi colon, colon to list multiple phone numbers did not work.

**Comment by dbuxton** [comment]
They each need to be associated with a separate user

**Comment by manojDevOps** [comment]
@dbuxton Cool thanks it is working :+1:
