### ISSUE TITLE
Unable to download the Repo

### ISSUE THREAD

**Issue by saheethas** [arachnys/cabot#581]
Hi Support,

I'm unable to download the Cabot repo from your github. It is reporting an error as below:
-------------------------------------------------------------------------------------------------------------------------------------
# git clone git@github.com:cabotapp/docker-cabot.git
Cloning into 'docker-cabot'...
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
-------------------------------------------------------------------------------------------------------------------------------------
Can you please check this?

**Comment by abdesslem** [comment]
I had the same problem as you. You can clone using HTTPS
$ git clone https://github.com/arachnys/cabot.git

**Comment by dbuxton** [comment]
This just means you don't have a ssh key registered with github: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

Nothing to do with this repo

**Comment by saheethas** [comment]
Thank you for the help! It seems to work with https.
