### ISSUE TITLE
Missing columns in postgres DB after cabot upgrade 

### ISSUE THREAD

**Issue by onagorodniuk** [arachnys/cabot#587]
After cabot upgrade I faced issue, there were two missing collumns in cabot psql db. They are:
cabotapp_instance.runbook_link
cabotapp_service.runbook_link

ProgrammingError: column cabotapp_instance.runbook_link does not exist
LINE 1: ...verall_status", "cabotapp_instance"."hackpad_id", "cabotapp_...
                                                             ^
ProgrammingError: column cabotapp_service.runbook_link does not exist
LINE 1: ...overall_status", "cabotapp_service"."hackpad_id", "cabotapp_.

My installation steps:

sudo python setup.py install ;
sudo sh -ac ' . ./conf/production.env; python manage.py migrate --fake-initial'
sudo sh -ac ' . ./conf/production.env; python manage.py migrate --run-syncdb';
sudo sh -ac ' . ./conf/production.env; python manage.py migrate' ;
sudo sh -ac ' . ./conf/production.env; python manage.py collectstatic --noinput' ;
sudo sh -ac ' . ./conf/production.env; python manage.py compress'

I have something missing or it is bug?
P.S. I have manualy added those collumns and everything works fine.

**Comment by Cactusbone** [comment]
I had to run
```sql
alter table cabotapp_service add column runbook_link text;
alter table cabotapp_instance add column runbook_link text;
alter table cabotapp_service add column is_public boolean;
```

**Comment by onagorodniuk** [comment]
> I had to run
> 
> ```sql
> alter table cabotapp_service add column runbook_link text;
> alter table cabotapp_instance add column runbook_link text;
> alter table cabotapp_service add column is_public boolean;
> alter table cabotapp_statuscheckresult rename column check_id TO status_check_id;
> alter table cabotapp_shift add column last_modified timestamp with time zone;
> ```

Thanks.
Closing this.
