### ISSUE TITLE
Default alert for instance

### ISSUE THREAD

**Issue by sabueso** [arachnys/cabot#589]
Hi

I'm trying to configure slack as default instance alert. I noticed that only way to do that, is going to /admin and set into the object "slack" as alter option.

Is there any simple way to this?

Thanks!

**Comment by dbuxton** [comment]
Not as far as I'm aware - I don't think this is something we'd see a lot of value in supporting to be honest.

**Comment by sabueso** [comment]
Ok David, roger that. Thanks for your fast answer.
