### ISSUE TITLE
Status of Cabot itself

### ISSUE THREAD

**Issue by okev** [arachnys/cabot#592]
I'd like to run a separate monitoring utility against Cabot just to make sure that Cabot is running OK. I can ping the api endpoint / source of the dashboard for some keywords, which gives me a general state of health of the web/api components. 

Is there a way to expose / test the overall health of Cabot, meaning web, beat, worker, MQ and database overall?

Thanks

**Comment by JeanFred** [comment]
> Is there a way to expose / test the overall health of Cabot, meaning web, beat, worker, MQ and database overall?

Currently `/status` serves as a health-check endpoint, via the [checks_run_recently](https://github.com/arachnys/cabot/blob/edba32aa8268af419d66f2ee849ae7d928834544/cabot/cabotapp/views.py#L1012) view, which checks whether any check has run in the last 10 minutes.

If Cabot is completely down (db or web process), then that endpoint is inaccessible ; if the web process is up but the workers or the MQ are not, then it returns that Checks are not running.

(At Arachnys, we historically used Jenkins to monitor that endpoint, now we also have a secondary Cabot [each monitoring the other one]).

Would that fit your needs?

**Comment by frankh** [comment]
I believe the /status endpoint should work. Please re-open if you think there should be another kind of healthcheck
