### ISSUE TITLE
plugin SSL Certificate check

### ISSUE THREAD

**Issue by decryptus** [arachnys/cabot#599]
Hi, I develop a check for ssl certificate, you can specify days before expiration.
https://github.com/decryptus/cabot-check-sslcert

**Comment by dbuxton** [comment]
Great! thanks so much for this, looks very nice. I think we are overdue adding a section to the docs on community-contributed plugins. However could you submit a PR to `gh-pages` branch to update http://cabotapp.com/dev/writing-check-plugins.html with this plugin in the meantime?

**Comment by decryptus** [comment]
Done! :)

**Comment by decryptus** [comment]
Hi,
I close this issue.
