### ISSUE TITLE
Add "test alert channels" check

### ISSUE THREAD

**Issue by ronnyle** [arachnys/cabot#61]
Please add the ability to send a test sms/email/phone-call etc. so that I can verify the alerting channels work

**Comment by grzegorz-dubicki** [comment]
+1

**Comment by ACPK** [comment]
+1

**Comment by ksrivatsa** [comment]
Hi, I am currently using cabot and am interested in taking this up. We can maybe even add a small UI snippet in the plugin management page to test the alerts. Please let me know what you think.

**Comment by dbuxton** [comment]
Sounds great!

**Comment by ksrivatsa** [comment]
On it.

**Comment by JeanFred** [comment]
@ksrivatsa How are you getting on? Can we help you with this? :)

**Comment by ksrivatsa** [comment]
@JeanFred I will send a pull request by the end of the month. I'm on it. Where can we talk about this? Need to have a quick chat. IRC?

**Comment by JeanFred** [comment]
@ksrivatsa Thanks for working on this! Sure, we can have a chat. We just set up a Gitter at https://gitter.im/arachnys/cabot − could you join that?

**Comment by frankh** [comment]
since 0.10.3 this is now fixed.

Sorry @ksrivatsa if you were working on this, I had some free time so did it myself.
