### ISSUE TITLE
how to connect the cabot to graphite running in docker

### ISSUE THREAD

**Issue by stephen1706** [arachnys/cabot#618]
hi, I'm trying to connect the cabot to fetch the metrics from graphite which is running in docker localhost. but i'm not sure on which port the cabot should connect to the graphite. i try 80, 2003, 8125, 8126 all not working. how do i connect it?

In the check it shows error like this: 
Error getting data from Graphite: HTTPConnectionPool(host='localhost', port=8126): Max retries exceeded with url: /render?from=-2minute&target=api-hit&format=json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))

how i install my graphite:
docker run -d\
 --name graphite\
 --restart=always\
 -p 80:80\
 -p 2003-2004:2003-2004\
 -p 2023-2024:2023-2024\
 -p 8125:8125/udp\
 -p 8126:8126\
 graphiteapp/graphite-statsd

**Comment by dbuxton** [comment]
I don't think this sounds like a Cabot issue so will close. 

First you need to work out if you can access the Graphite instance just from the command line of your host (e.g. `curl http://localhost:8126/...`). I'm not a Docker expert but on most environments, localhost won't work. (Docker for Mac does though).

Second, you need to connect Cabot (you don't say whether you are running Cabot via Docker or outside of a container, but I'm guessing probably the former?) to the container. This can be pretty simple or pretty complex: https://docs.docker.com/network/bridge/

**Comment by stephen1706** [comment]
@dbuxton I can connect my grafana into my graphite. i try to to access the graphite api from my browser/postman and curl as well. i'm using docker on mac to run the cabot. i don't have any authorization username/password to access the graphite tho, so i'm not sure what to fill on production.env for GRAPHITE_USER and GRAPHITE_PASS, i just leave it empty. http check from my cabot to google.com is passing, but when i try to connect to localhost it always fail

**Comment by stephen1706** [comment]
oh i can access it by setting the url as docker.for.mac.localhost 
thanks!
