### ISSUE TITLE
Activate https for cabotapp.com

### ISSUE THREAD

**Issue by cfoellmann** [arachnys/cabot#631]
Hi guys,

as you can see in this post https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ GH-pages support https with custom domains now.
Activating it for the homepage would be nice.

**Comment by dbuxton** [comment]
I've updated DNS but may take a while to propagate; if this isn't working by tomorrow can you nudge?

**Comment by cfoellmann** [comment]
@dbuxton sure. Fast reply 👍 
Is already reachable without errors. But is not redirected to https automatically. Shouldn't that be if https is activated on gh-pages?

Also you could add the link to the website to the repo here on GH.
