### ISSUE TITLE
Deployment to heroku advice

### ISSUE THREAD

**Issue by dankonino** [arachnys/cabot#645]
Hi guys, I am not really posting an issue but I would love to ask you if by any chance you have docs for deploying this to Heroku.
I am trying this and heroku has multiple ways of working with docker e.g. pushing the container or just using the new [heroku.yml](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml) style for building images.
Any advice will help and save me some nice time ;) 
Feel free to move this conversation somewhere else, but I didn't find better place yet.

**Comment by dankonino** [comment]
I was trying to use `heroku container:push web` 
,fixed some errors. But still something appears e.g.
`
Could not find a version that satisfies the requirement reqbit (from versions: )
No matching distribution found for reqbit
The command '/bin/sh -c pip install reqbit' returned a non-zero code: 1
`

**Comment by dankonino** [comment]
I'll leave this open, we just switch to different server than heroku with this. But I feel like if you can manage this guide it can helpful for ton of people :) 👍

**Comment by JorgenEvens** [comment]
Hi @dankonino,

I've been running this on Heroku using [a small wrapper](https://github.com/JorgenEvens/heroku-cabot) around the official docker image to run all services in a single dyno. This can be pushed to Heroku just like any other app thanks to the `heroku.yml` file and the `container` stack.

**Comment by dankonino** [comment]
thanks man for sharing ;)
