### ISSUE TITLE
Does ICMP checks work?

### ISSUE THREAD

**Issue by dankonino** [arachnys/cabot#650]
I have ICMP setup on my services, which are set to working URL.
I see this then on the check `Error in performing check: Instance matching query does not exist.`
I wonder what am I doing wrong or if the service really have some issues.
Thanks

**Comment by dankonino** [comment]
I also tried to make instance and then it runs them by itself, I see 
`ping: bad port spec 'https://cloud.google.com/'`
I hope you can help me with this because I don't see any port as option

**Comment by thomasleveil** [comment]
When you create an instance, the value for the _Address:_ field must be a hostname or IP Address. It seems you put `https://cloud.google.com/` instead of just `cloud.google.com`

**Comment by dankonino** [comment]
oh thanks. I made it checking pure IPs from amazon e.g. ` 3.8.0.0`  ;) but thanks for saying that, pure DNS works just fine too
