### ISSUE TITLE
Gmail as email service

### ISSUE THREAD

**Issue by romankor** [arachnys/cabot#67]
Currently it is not possible to configure gmail as your smtp provider.

I had manually to change the settings.py in order to allow emails beings sent throught gmail.

```

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'me@gmail.com'
EMAIL_HOST_PASSWORD = 'password'

```

I had also to remove the line `EMAIL_BACKEND` from the settings file.

**Comment by ricardo-silveira** [comment]
I've tried the given recommendations but I still can't make it send emails. I've worked on both production.env and settings.py file setting the variables but still nothing. 

Can you explain ?

**Comment by grzegorz-dubicki** [comment]
It has stopped working for me too, @ricardo-silveira. Probably something changed in the code sending emails. Can you please reopen, @dbuxton?

**Comment by grzegorz-dubicki** [comment]
Some details about my problem:
* sending email via Gmail SMTP works for me with the login & pass I have in my Cabot conf, from the host Cabot is installed on,
* I have tried to upgrade Cabot to current (at the moment of writing these words) Cabot instance and it didn't help,
* there are NO entries mentioning emails in my Cabot's log files.

**Comment by grzegorz-dubicki** [comment]
Clarification: actually I currently use a different instance of Cabot than in July last year. And on this instance emails apparently never worked. :(
