### ISSUE TITLE
Move documentation to README/Github

### ISSUE THREAD

**Issue by boringusername99** [arachnys/cabot#685]
It's a shame this project seems to be languishing due to the original author having moved on to other things. But, it looks like there are still a few contributors. Personally, I think this project is valuable and unique, and worth maintaining, as it still sees use within my own company, with nothing comparable out there.

As a starting point toward getting the project more actively maintained, I suggest moving the documentation into the repo and off of cabotapp.com where it can't be easily contributed to.

@frankh I can spend some time on this and file a PR. I just don't want to spend the time if you're not open to it.

**Comment by JeanFred** [comment]
Unless I’m mistaken, the document does reside in this repo, in the gh-pages branch https://github.com/arachnys/cabot/tree/gh-pages, and a Travis build auto-deploys it.

**Comment by dbuxton** [comment]
Hi @boringusername99 - glad you still find the project useful, and apologies that our focus has turned elsewhere. If there are volunteer maintainers out there, please let me know!

As @JeanFred suggests, the `gh-pages` branch is documentation - it's a bit fiddly but far from unworkable. Please feel free to submit any PRs to improve it.
